//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.09 at 11:40:32 AM CST 
//


package gov.va.vba.rbps.services.ws.client.mapping.awards.amend;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for documentReturnVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentReturnVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://session.ejb.awards.benefits.vba.va.gov/}voReturnBase">
 *       &lt;sequence>
 *         &lt;element name="documentList" type="{http://session.ejb.awards.benefits.vba.va.gov/}documentVO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentReturnVO", propOrder = {
    "documentList"
})
public class DocumentReturnVO
    extends VoReturnBase
{

    @XmlElement(nillable = true)
    protected List<DocumentVO> documentList;

    /**
     * Gets the value of the documentList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentVO }
     * 
     * 
     */
    public List<DocumentVO> getDocumentList() {
        if (documentList == null) {
            documentList = new ArrayList<DocumentVO>();
        }
        return this.documentList;
    }

}
