//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.09 at 08:46:31 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://session.ejb.cp.benefits.vba.va.gov/")
package gov.va.vba.rbps.services.ws.client.mapping.awards.militarypay;
