//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.31 at 10:36:09 AM CST 
//


package gov.va.vba.rbps.services.ws.client.mapping.vonapp.userinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for vnpPtcpnt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vnpPtcpnt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="corpPtcpntId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="fraudInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jrnDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="jrnLctnId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jrnObjId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jrnStatusTypeCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jrnUserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="legacyPoaCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="miscVendorInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ptcpntShortNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ptcpntTypeNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxIdfctnNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tinWaiverReasonTypeCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vnpProcId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="vnpPtcpntId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vnpPtcpnt", propOrder = {
    "corpPtcpntId",
    "fraudInd",
    "jrnDt",
    "jrnLctnId",
    "jrnObjId",
    "jrnStatusTypeCd",
    "jrnUserId",
    "legacyPoaCd",
    "miscVendorInd",
    "ptcpntShortNm",
    "ptcpntTypeNm",
    "taxIdfctnNbr",
    "tinWaiverReasonTypeCd",
    "vnpProcId",
    "vnpPtcpntId"
})
public class VnpPtcpnt {

    protected Long corpPtcpntId;
    protected String fraudInd;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar jrnDt;
    protected String jrnLctnId;
    protected String jrnObjId;
    protected String jrnStatusTypeCd;
    protected String jrnUserId;
    protected String legacyPoaCd;
    protected String miscVendorInd;
    protected String ptcpntShortNm;
    protected String ptcpntTypeNm;
    protected String taxIdfctnNbr;
    protected String tinWaiverReasonTypeCd;
    protected Long vnpProcId;
    protected long vnpPtcpntId;

    /**
     * Gets the value of the corpPtcpntId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCorpPtcpntId() {
        return corpPtcpntId;
    }

    /**
     * Sets the value of the corpPtcpntId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCorpPtcpntId(Long value) {
        this.corpPtcpntId = value;
    }

    /**
     * Gets the value of the fraudInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudInd() {
        return fraudInd;
    }

    /**
     * Sets the value of the fraudInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudInd(String value) {
        this.fraudInd = value;
    }

    /**
     * Gets the value of the jrnDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getJrnDt() {
        return jrnDt;
    }

    /**
     * Sets the value of the jrnDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setJrnDt(XMLGregorianCalendar value) {
        this.jrnDt = value;
    }

    /**
     * Gets the value of the jrnLctnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJrnLctnId() {
        return jrnLctnId;
    }

    /**
     * Sets the value of the jrnLctnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJrnLctnId(String value) {
        this.jrnLctnId = value;
    }

    /**
     * Gets the value of the jrnObjId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJrnObjId() {
        return jrnObjId;
    }

    /**
     * Sets the value of the jrnObjId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJrnObjId(String value) {
        this.jrnObjId = value;
    }

    /**
     * Gets the value of the jrnStatusTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJrnStatusTypeCd() {
        return jrnStatusTypeCd;
    }

    /**
     * Sets the value of the jrnStatusTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJrnStatusTypeCd(String value) {
        this.jrnStatusTypeCd = value;
    }

    /**
     * Gets the value of the jrnUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJrnUserId() {
        return jrnUserId;
    }

    /**
     * Sets the value of the jrnUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJrnUserId(String value) {
        this.jrnUserId = value;
    }

    /**
     * Gets the value of the legacyPoaCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegacyPoaCd() {
        return legacyPoaCd;
    }

    /**
     * Sets the value of the legacyPoaCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegacyPoaCd(String value) {
        this.legacyPoaCd = value;
    }

    /**
     * Gets the value of the miscVendorInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiscVendorInd() {
        return miscVendorInd;
    }

    /**
     * Sets the value of the miscVendorInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiscVendorInd(String value) {
        this.miscVendorInd = value;
    }

    /**
     * Gets the value of the ptcpntShortNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtcpntShortNm() {
        return ptcpntShortNm;
    }

    /**
     * Sets the value of the ptcpntShortNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtcpntShortNm(String value) {
        this.ptcpntShortNm = value;
    }

    /**
     * Gets the value of the ptcpntTypeNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtcpntTypeNm() {
        return ptcpntTypeNm;
    }

    /**
     * Sets the value of the ptcpntTypeNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtcpntTypeNm(String value) {
        this.ptcpntTypeNm = value;
    }

    /**
     * Gets the value of the taxIdfctnNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIdfctnNbr() {
        return taxIdfctnNbr;
    }

    /**
     * Sets the value of the taxIdfctnNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIdfctnNbr(String value) {
        this.taxIdfctnNbr = value;
    }

    /**
     * Gets the value of the tinWaiverReasonTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTinWaiverReasonTypeCd() {
        return tinWaiverReasonTypeCd;
    }

    /**
     * Sets the value of the tinWaiverReasonTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTinWaiverReasonTypeCd(String value) {
        this.tinWaiverReasonTypeCd = value;
    }

    /**
     * Gets the value of the vnpProcId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVnpProcId() {
        return vnpProcId;
    }

    /**
     * Sets the value of the vnpProcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVnpProcId(Long value) {
        this.vnpProcId = value;
    }

    /**
     * Gets the value of the vnpPtcpntId property.
     * 
     */
    public long getVnpPtcpntId() {
        return vnpPtcpntId;
    }

    /**
     * Sets the value of the vnpPtcpntId property.
     * 
     */
    public void setVnpPtcpntId(long value) {
        this.vnpPtcpntId = value;
    }

}
