//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.27 at 04:46:15 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.share.benefits.vba.va.gov/")
package gov.va.vba.rbps.services.ws.client.mapping.share.findratings;
