//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.22 at 01:21:30 PM EDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.awardDoc.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for individualUnemployabilityVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="individualUnemployabilityVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://gov.va.vba.benefits.awards.ws/services}voBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="beginDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="deprecatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="effectiveDateOverrideType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="effectiveDateOverrideTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="effectiveEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="endDateOverrideInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endDateOverrideType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endDateOverrideTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="individualUnemployabilityDecisionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="individualUnemployabilityDecisionTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="modifiedAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="modifiedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="modifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="modifiedLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="modifiedProcess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="overrideActionInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="overrideBeginDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="overrideDecisionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="overrideEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="previousRatingDecisionID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="profileDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ratingDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ratingDecisionId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="rbaIssueId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="supplementalDecisionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="supplementalDecisionTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="veteranParticipantId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "individualUnemployabilityVO", propOrder = {
    "beginDate",
    "deprecatedDate",
    "effectiveDate",
    "effectiveDateOverrideType",
    "effectiveDateOverrideTypeDesc",
    "effectiveEndDate",
    "endDate",
    "endDateOverrideInd",
    "endDateOverrideType",
    "endDateOverrideTypeDesc",
    "individualUnemployabilityDecisionType",
    "individualUnemployabilityDecisionTypeDesc",
    "modifiedAction",
    "modifiedBy",
    "modifiedDate",
    "modifiedLocation",
    "modifiedProcess",
    "overrideActionInd",
    "overrideBeginDate",
    "overrideDecisionDate",
    "overrideEndDate",
    "previousRatingDecisionID",
    "profileDate",
    "ratingDate",
    "ratingDecisionId",
    "rbaIssueId",
    "supplementalDecisionType",
    "supplementalDecisionTypeDesc",
    "veteranParticipantId"
})
public class IndividualUnemployabilityVO
    extends VoBase
{

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar beginDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deprecatedDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar effectiveDate;
    protected String effectiveDateOverrideType;
    protected String effectiveDateOverrideTypeDesc;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar effectiveEndDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    protected String endDateOverrideInd;
    protected String endDateOverrideType;
    protected String endDateOverrideTypeDesc;
    protected String individualUnemployabilityDecisionType;
    protected String individualUnemployabilityDecisionTypeDesc;
    protected String modifiedAction;
    protected String modifiedBy;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifiedDate;
    protected String modifiedLocation;
    protected String modifiedProcess;
    protected String overrideActionInd;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar overrideBeginDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar overrideDecisionDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar overrideEndDate;
    protected Long previousRatingDecisionID;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar profileDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ratingDate;
    protected Long ratingDecisionId;
    protected Long rbaIssueId;
    protected String supplementalDecisionType;
    protected String supplementalDecisionTypeDesc;
    protected Long veteranParticipantId;

    /**
     * Gets the value of the beginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBeginDate() {
        return beginDate;
    }

    /**
     * Sets the value of the beginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBeginDate(XMLGregorianCalendar value) {
        this.beginDate = value;
    }

    /**
     * Gets the value of the deprecatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeprecatedDate() {
        return deprecatedDate;
    }

    /**
     * Sets the value of the deprecatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeprecatedDate(XMLGregorianCalendar value) {
        this.deprecatedDate = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the effectiveDateOverrideType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDateOverrideType() {
        return effectiveDateOverrideType;
    }

    /**
     * Sets the value of the effectiveDateOverrideType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDateOverrideType(String value) {
        this.effectiveDateOverrideType = value;
    }

    /**
     * Gets the value of the effectiveDateOverrideTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDateOverrideTypeDesc() {
        return effectiveDateOverrideTypeDesc;
    }

    /**
     * Sets the value of the effectiveDateOverrideTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDateOverrideTypeDesc(String value) {
        this.effectiveDateOverrideTypeDesc = value;
    }

    /**
     * Gets the value of the effectiveEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveEndDate() {
        return effectiveEndDate;
    }

    /**
     * Sets the value of the effectiveEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveEndDate(XMLGregorianCalendar value) {
        this.effectiveEndDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the endDateOverrideInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDateOverrideInd() {
        return endDateOverrideInd;
    }

    /**
     * Sets the value of the endDateOverrideInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDateOverrideInd(String value) {
        this.endDateOverrideInd = value;
    }

    /**
     * Gets the value of the endDateOverrideType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDateOverrideType() {
        return endDateOverrideType;
    }

    /**
     * Sets the value of the endDateOverrideType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDateOverrideType(String value) {
        this.endDateOverrideType = value;
    }

    /**
     * Gets the value of the endDateOverrideTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDateOverrideTypeDesc() {
        return endDateOverrideTypeDesc;
    }

    /**
     * Sets the value of the endDateOverrideTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDateOverrideTypeDesc(String value) {
        this.endDateOverrideTypeDesc = value;
    }

    /**
     * Gets the value of the individualUnemployabilityDecisionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualUnemployabilityDecisionType() {
        return individualUnemployabilityDecisionType;
    }

    /**
     * Sets the value of the individualUnemployabilityDecisionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualUnemployabilityDecisionType(String value) {
        this.individualUnemployabilityDecisionType = value;
    }

    /**
     * Gets the value of the individualUnemployabilityDecisionTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualUnemployabilityDecisionTypeDesc() {
        return individualUnemployabilityDecisionTypeDesc;
    }

    /**
     * Sets the value of the individualUnemployabilityDecisionTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualUnemployabilityDecisionTypeDesc(String value) {
        this.individualUnemployabilityDecisionTypeDesc = value;
    }

    /**
     * Gets the value of the modifiedAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedAction() {
        return modifiedAction;
    }

    /**
     * Sets the value of the modifiedAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedAction(String value) {
        this.modifiedAction = value;
    }

    /**
     * Gets the value of the modifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * Sets the value of the modifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedBy(String value) {
        this.modifiedBy = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedDate(XMLGregorianCalendar value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the modifiedLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedLocation() {
        return modifiedLocation;
    }

    /**
     * Sets the value of the modifiedLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedLocation(String value) {
        this.modifiedLocation = value;
    }

    /**
     * Gets the value of the modifiedProcess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedProcess() {
        return modifiedProcess;
    }

    /**
     * Sets the value of the modifiedProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedProcess(String value) {
        this.modifiedProcess = value;
    }

    /**
     * Gets the value of the overrideActionInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverrideActionInd() {
        return overrideActionInd;
    }

    /**
     * Sets the value of the overrideActionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverrideActionInd(String value) {
        this.overrideActionInd = value;
    }

    /**
     * Gets the value of the overrideBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOverrideBeginDate() {
        return overrideBeginDate;
    }

    /**
     * Sets the value of the overrideBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOverrideBeginDate(XMLGregorianCalendar value) {
        this.overrideBeginDate = value;
    }

    /**
     * Gets the value of the overrideDecisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOverrideDecisionDate() {
        return overrideDecisionDate;
    }

    /**
     * Sets the value of the overrideDecisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOverrideDecisionDate(XMLGregorianCalendar value) {
        this.overrideDecisionDate = value;
    }

    /**
     * Gets the value of the overrideEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOverrideEndDate() {
        return overrideEndDate;
    }

    /**
     * Sets the value of the overrideEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOverrideEndDate(XMLGregorianCalendar value) {
        this.overrideEndDate = value;
    }

    /**
     * Gets the value of the previousRatingDecisionID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPreviousRatingDecisionID() {
        return previousRatingDecisionID;
    }

    /**
     * Sets the value of the previousRatingDecisionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPreviousRatingDecisionID(Long value) {
        this.previousRatingDecisionID = value;
    }

    /**
     * Gets the value of the profileDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProfileDate() {
        return profileDate;
    }

    /**
     * Sets the value of the profileDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProfileDate(XMLGregorianCalendar value) {
        this.profileDate = value;
    }

    /**
     * Gets the value of the ratingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRatingDate() {
        return ratingDate;
    }

    /**
     * Sets the value of the ratingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRatingDate(XMLGregorianCalendar value) {
        this.ratingDate = value;
    }

    /**
     * Gets the value of the ratingDecisionId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRatingDecisionId() {
        return ratingDecisionId;
    }

    /**
     * Sets the value of the ratingDecisionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRatingDecisionId(Long value) {
        this.ratingDecisionId = value;
    }

    /**
     * Gets the value of the rbaIssueId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRbaIssueId() {
        return rbaIssueId;
    }

    /**
     * Sets the value of the rbaIssueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRbaIssueId(Long value) {
        this.rbaIssueId = value;
    }

    /**
     * Gets the value of the supplementalDecisionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplementalDecisionType() {
        return supplementalDecisionType;
    }

    /**
     * Sets the value of the supplementalDecisionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplementalDecisionType(String value) {
        this.supplementalDecisionType = value;
    }

    /**
     * Gets the value of the supplementalDecisionTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplementalDecisionTypeDesc() {
        return supplementalDecisionTypeDesc;
    }

    /**
     * Sets the value of the supplementalDecisionTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplementalDecisionTypeDesc(String value) {
        this.supplementalDecisionTypeDesc = value;
    }

    /**
     * Gets the value of the veteranParticipantId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVeteranParticipantId() {
        return veteranParticipantId;
    }

    /**
     * Sets the value of the veteranParticipantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVeteranParticipantId(Long value) {
        this.veteranParticipantId = value;
    }

}
