//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.11 at 09:35:49 AM EST 
//


package gov.va.vba.vbmsc.services.ws.client.mapping.awardData.service;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for awardLineRecipientVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="awardLineRecipientVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="awardAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="personalFundsOfPatientAwardAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="recipientParticipantID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "awardLineRecipientVO", propOrder = {
    "awardAmount",
    "personalFundsOfPatientAwardAmount",
    "recipientParticipantID"
})
public class AwardLineRecipientVO {

    protected BigDecimal awardAmount;
    protected BigDecimal personalFundsOfPatientAwardAmount;
    protected Long recipientParticipantID;

    /**
     * Gets the value of the awardAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAwardAmount() {
        return awardAmount;
    }

    /**
     * Sets the value of the awardAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAwardAmount(BigDecimal value) {
        this.awardAmount = value;
    }

    /**
     * Gets the value of the personalFundsOfPatientAwardAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPersonalFundsOfPatientAwardAmount() {
        return personalFundsOfPatientAwardAmount;
    }

    /**
     * Sets the value of the personalFundsOfPatientAwardAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPersonalFundsOfPatientAwardAmount(BigDecimal value) {
        this.personalFundsOfPatientAwardAmount = value;
    }

    /**
     * Gets the value of the recipientParticipantID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRecipientParticipantID() {
        return recipientParticipantID;
    }

    /**
     * Sets the value of the recipientParticipantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRecipientParticipantID(Long value) {
        this.recipientParticipantID = value;
    }

}
