//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.11 at 09:35:49 AM EST 
//


package gov.va.vba.vbmsc.services.ws.client.mapping.awardData.service;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for awardEventVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="awardEventVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="authorizedByUserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="authorizedByUserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="authorizedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="awardEventID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="awardEventStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="awardEventType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="awardEventTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="awardGenerationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="awardOverrideIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="awardPrintRemarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="concurrentRetirementDisabilityPayIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="controlDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstChangedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gaoPrintRemarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="generatedByUserID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="generatedByUserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="generationBatchType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="generationBatchTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="generationProcessType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="generationProcessTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="processingStationLocationID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="processingStationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ratingAwardSummaryID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="retroAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="stationOfJurisdictionLocationID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="stationOfJurisdictionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "awardEventVO", propOrder = {
    "authorizedByUserId",
    "authorizedByUserName",
    "authorizedDate",
    "awardEventID",
    "awardEventStatus",
    "awardEventType",
    "awardEventTypeDesc",
    "awardGenerationDate",
    "awardOverrideIndicator",
    "awardPrintRemarks",
    "concurrentRetirementDisabilityPayIndicator",
    "controlDate",
    "firstChangedDate",
    "gaoPrintRemarks",
    "generatedByUserID",
    "generatedByUserName",
    "generationBatchType",
    "generationBatchTypeDesc",
    "generationProcessType",
    "generationProcessTypeDesc",
    "processingStationLocationID",
    "processingStationNumber",
    "ratingAwardSummaryID",
    "retroAmount",
    "stationOfJurisdictionLocationID",
    "stationOfJurisdictionNumber"
})
@XmlSeeAlso({
    HAwardEventVO.class
})
public class AwardEventVO {

    protected String authorizedByUserId;
    protected String authorizedByUserName;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar authorizedDate;
    protected Long awardEventID;
    protected String awardEventStatus;
    protected String awardEventType;
    protected String awardEventTypeDesc;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar awardGenerationDate;
    protected String awardOverrideIndicator;
    protected String awardPrintRemarks;
    protected String concurrentRetirementDisabilityPayIndicator;
    protected String controlDate;
    protected String firstChangedDate;
    protected String gaoPrintRemarks;
    protected String generatedByUserID;
    protected String generatedByUserName;
    protected String generationBatchType;
    protected String generationBatchTypeDesc;
    protected String generationProcessType;
    protected String generationProcessTypeDesc;
    protected Long processingStationLocationID;
    protected String processingStationNumber;
    protected Long ratingAwardSummaryID;
    protected BigDecimal retroAmount;
    protected Long stationOfJurisdictionLocationID;
    protected String stationOfJurisdictionNumber;

    /**
     * Gets the value of the authorizedByUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedByUserId() {
        return authorizedByUserId;
    }

    /**
     * Sets the value of the authorizedByUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedByUserId(String value) {
        this.authorizedByUserId = value;
    }

    /**
     * Gets the value of the authorizedByUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedByUserName() {
        return authorizedByUserName;
    }

    /**
     * Sets the value of the authorizedByUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedByUserName(String value) {
        this.authorizedByUserName = value;
    }

    /**
     * Gets the value of the authorizedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAuthorizedDate() {
        return authorizedDate;
    }

    /**
     * Sets the value of the authorizedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAuthorizedDate(XMLGregorianCalendar value) {
        this.authorizedDate = value;
    }

    /**
     * Gets the value of the awardEventID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAwardEventID() {
        return awardEventID;
    }

    /**
     * Sets the value of the awardEventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAwardEventID(Long value) {
        this.awardEventID = value;
    }

    /**
     * Gets the value of the awardEventStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardEventStatus() {
        return awardEventStatus;
    }

    /**
     * Sets the value of the awardEventStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardEventStatus(String value) {
        this.awardEventStatus = value;
    }

    /**
     * Gets the value of the awardEventType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardEventType() {
        return awardEventType;
    }

    /**
     * Sets the value of the awardEventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardEventType(String value) {
        this.awardEventType = value;
    }

    /**
     * Gets the value of the awardEventTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardEventTypeDesc() {
        return awardEventTypeDesc;
    }

    /**
     * Sets the value of the awardEventTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardEventTypeDesc(String value) {
        this.awardEventTypeDesc = value;
    }

    /**
     * Gets the value of the awardGenerationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAwardGenerationDate() {
        return awardGenerationDate;
    }

    /**
     * Sets the value of the awardGenerationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAwardGenerationDate(XMLGregorianCalendar value) {
        this.awardGenerationDate = value;
    }

    /**
     * Gets the value of the awardOverrideIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardOverrideIndicator() {
        return awardOverrideIndicator;
    }

    /**
     * Sets the value of the awardOverrideIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardOverrideIndicator(String value) {
        this.awardOverrideIndicator = value;
    }

    /**
     * Gets the value of the awardPrintRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardPrintRemarks() {
        return awardPrintRemarks;
    }

    /**
     * Sets the value of the awardPrintRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardPrintRemarks(String value) {
        this.awardPrintRemarks = value;
    }

    /**
     * Gets the value of the concurrentRetirementDisabilityPayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcurrentRetirementDisabilityPayIndicator() {
        return concurrentRetirementDisabilityPayIndicator;
    }

    /**
     * Sets the value of the concurrentRetirementDisabilityPayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcurrentRetirementDisabilityPayIndicator(String value) {
        this.concurrentRetirementDisabilityPayIndicator = value;
    }

    /**
     * Gets the value of the controlDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlDate() {
        return controlDate;
    }

    /**
     * Sets the value of the controlDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlDate(String value) {
        this.controlDate = value;
    }

    /**
     * Gets the value of the firstChangedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstChangedDate() {
        return firstChangedDate;
    }

    /**
     * Sets the value of the firstChangedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstChangedDate(String value) {
        this.firstChangedDate = value;
    }

    /**
     * Gets the value of the gaoPrintRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGaoPrintRemarks() {
        return gaoPrintRemarks;
    }

    /**
     * Sets the value of the gaoPrintRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGaoPrintRemarks(String value) {
        this.gaoPrintRemarks = value;
    }

    /**
     * Gets the value of the generatedByUserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratedByUserID() {
        return generatedByUserID;
    }

    /**
     * Sets the value of the generatedByUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratedByUserID(String value) {
        this.generatedByUserID = value;
    }

    /**
     * Gets the value of the generatedByUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratedByUserName() {
        return generatedByUserName;
    }

    /**
     * Sets the value of the generatedByUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratedByUserName(String value) {
        this.generatedByUserName = value;
    }

    /**
     * Gets the value of the generationBatchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerationBatchType() {
        return generationBatchType;
    }

    /**
     * Sets the value of the generationBatchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerationBatchType(String value) {
        this.generationBatchType = value;
    }

    /**
     * Gets the value of the generationBatchTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerationBatchTypeDesc() {
        return generationBatchTypeDesc;
    }

    /**
     * Sets the value of the generationBatchTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerationBatchTypeDesc(String value) {
        this.generationBatchTypeDesc = value;
    }

    /**
     * Gets the value of the generationProcessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerationProcessType() {
        return generationProcessType;
    }

    /**
     * Sets the value of the generationProcessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerationProcessType(String value) {
        this.generationProcessType = value;
    }

    /**
     * Gets the value of the generationProcessTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerationProcessTypeDesc() {
        return generationProcessTypeDesc;
    }

    /**
     * Sets the value of the generationProcessTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerationProcessTypeDesc(String value) {
        this.generationProcessTypeDesc = value;
    }

    /**
     * Gets the value of the processingStationLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getProcessingStationLocationID() {
        return processingStationLocationID;
    }

    /**
     * Sets the value of the processingStationLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProcessingStationLocationID(Long value) {
        this.processingStationLocationID = value;
    }

    /**
     * Gets the value of the processingStationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingStationNumber() {
        return processingStationNumber;
    }

    /**
     * Sets the value of the processingStationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingStationNumber(String value) {
        this.processingStationNumber = value;
    }

    /**
     * Gets the value of the ratingAwardSummaryID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRatingAwardSummaryID() {
        return ratingAwardSummaryID;
    }

    /**
     * Sets the value of the ratingAwardSummaryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRatingAwardSummaryID(Long value) {
        this.ratingAwardSummaryID = value;
    }

    /**
     * Gets the value of the retroAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRetroAmount() {
        return retroAmount;
    }

    /**
     * Sets the value of the retroAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRetroAmount(BigDecimal value) {
        this.retroAmount = value;
    }

    /**
     * Gets the value of the stationOfJurisdictionLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStationOfJurisdictionLocationID() {
        return stationOfJurisdictionLocationID;
    }

    /**
     * Sets the value of the stationOfJurisdictionLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStationOfJurisdictionLocationID(Long value) {
        this.stationOfJurisdictionLocationID = value;
    }

    /**
     * Gets the value of the stationOfJurisdictionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationOfJurisdictionNumber() {
        return stationOfJurisdictionNumber;
    }

    /**
     * Sets the value of the stationOfJurisdictionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationOfJurisdictionNumber(String value) {
        this.stationOfJurisdictionNumber = value;
    }

}
