//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.11 at 09:35:49 AM EST 
//


package gov.va.vba.vbmsc.services.ws.client.mapping.awardData.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hAwardEventDecisionVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hAwardEventDecisionVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://gov.va.vba.benefits.vbmsc/services}awardEventDecisionVO"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="allotmentDecnExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="allotmentDecnExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}allotmentDecnExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="basicEligibilityDecisionList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="basicEligibilityDecisionVO" type="{http://gov.va.vba.benefits.vbmsc/services}basicEligibilityDecisionVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="burialBeneDecnList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="burialBeneDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}burialBeneDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="burialBenefitDecnList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="burialBenefitDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}burialBenefitDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="burialSummaryDecnList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="burialSummaryDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}burialSummaryDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="clothingAllowanceDecnList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="clothingAllowanceDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}clothingAllowanceDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dependencyDecisionList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="dependencyDecisionVO" type="{http://gov.va.vba.benefits.vbmsc/services}dependencyDecisionVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="disabilityPayDecnExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="disabilityPayDecnExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}disabilityPayDecnExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dischargePayList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="dischargePayVO" type="{http://gov.va.vba.benefits.vbmsc/services}dischargePayVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="drillPayDecnList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="drillPayDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}drillPayDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="electionDecisionExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="electionDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}electionDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="expenseDecisionExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="expenseDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}expenseDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="finclDecnCustomList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="finclDecnCustomVO" type="{http://gov.va.vba.benefits.vbmsc/services}finclDecnCustomVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="fraudDecisionExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="fraudDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}fraudDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="incomeDecisionExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="incomeDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}incomeDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="instznAdjustmentDecisionExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="instznAdjustmentDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}instznAdjustmentDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="instznDecisionExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="instznDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}instznDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="medalOfHonorDecnExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="medalOfHonorDecnExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}medalOfHonorDecnExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="militaryEligibilityDecisionList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="militaryEligibilityDecisionVO" type="{http://gov.va.vba.benefits.vbmsc/services}militaryEligibilityDecisionVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="netWorthDecisionExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="netWorthDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}netWorthDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="otherWithholdingDecnExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="otherWithholdingDecnExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}otherWithholdingDecnExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="payRateDecisionExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="payRateDecisionExtendedListVO" type="{http://gov.va.vba.benefits.vbmsc/services}payRateDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="retirementPayDecisionList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="retirementPayDecisionVO" type="{http://gov.va.vba.benefits.vbmsc/services}retirementPayDecisionVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="separationPayDecisionExtendedList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="separationPayDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}separationPayDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hAwardEventDecisionVO", propOrder = {
    "allotmentDecnExtendedList",
    "basicEligibilityDecisionList",
    "burialBeneDecnList",
    "burialBenefitDecnList",
    "burialSummaryDecnList",
    "clothingAllowanceDecnList",
    "dependencyDecisionList",
    "disabilityPayDecnExtendedList",
    "dischargePayList",
    "drillPayDecnList",
    "electionDecisionExtendedList",
    "expenseDecisionExtendedList",
    "finclDecnCustomList",
    "fraudDecisionExtendedList",
    "incomeDecisionExtendedList",
    "instznAdjustmentDecisionExtendedList",
    "instznDecisionExtendedList",
    "medalOfHonorDecnExtendedList",
    "militaryEligibilityDecisionList",
    "netWorthDecisionExtendedList",
    "otherWithholdingDecnExtendedList",
    "payRateDecisionExtendedList",
    "retirementPayDecisionList",
    "separationPayDecisionExtendedList"
})
public class HAwardEventDecisionVO
    extends AwardEventDecisionVO
{

    protected HAwardEventDecisionVO.AllotmentDecnExtendedList allotmentDecnExtendedList;
    protected HAwardEventDecisionVO.BasicEligibilityDecisionList basicEligibilityDecisionList;
    protected HAwardEventDecisionVO.BurialBeneDecnList burialBeneDecnList;
    protected HAwardEventDecisionVO.BurialBenefitDecnList burialBenefitDecnList;
    protected HAwardEventDecisionVO.BurialSummaryDecnList burialSummaryDecnList;
    protected HAwardEventDecisionVO.ClothingAllowanceDecnList clothingAllowanceDecnList;
    protected HAwardEventDecisionVO.DependencyDecisionList dependencyDecisionList;
    protected HAwardEventDecisionVO.DisabilityPayDecnExtendedList disabilityPayDecnExtendedList;
    protected HAwardEventDecisionVO.DischargePayList dischargePayList;
    protected HAwardEventDecisionVO.DrillPayDecnList drillPayDecnList;
    protected HAwardEventDecisionVO.ElectionDecisionExtendedList electionDecisionExtendedList;
    protected HAwardEventDecisionVO.ExpenseDecisionExtendedList expenseDecisionExtendedList;
    protected HAwardEventDecisionVO.FinclDecnCustomList finclDecnCustomList;
    protected HAwardEventDecisionVO.FraudDecisionExtendedList fraudDecisionExtendedList;
    protected HAwardEventDecisionVO.IncomeDecisionExtendedList incomeDecisionExtendedList;
    protected HAwardEventDecisionVO.InstznAdjustmentDecisionExtendedList instznAdjustmentDecisionExtendedList;
    protected HAwardEventDecisionVO.InstznDecisionExtendedList instznDecisionExtendedList;
    protected HAwardEventDecisionVO.MedalOfHonorDecnExtendedList medalOfHonorDecnExtendedList;
    protected HAwardEventDecisionVO.MilitaryEligibilityDecisionList militaryEligibilityDecisionList;
    protected HAwardEventDecisionVO.NetWorthDecisionExtendedList netWorthDecisionExtendedList;
    protected HAwardEventDecisionVO.OtherWithholdingDecnExtendedList otherWithholdingDecnExtendedList;
    protected HAwardEventDecisionVO.PayRateDecisionExtendedList payRateDecisionExtendedList;
    protected HAwardEventDecisionVO.RetirementPayDecisionList retirementPayDecisionList;
    protected HAwardEventDecisionVO.SeparationPayDecisionExtendedList separationPayDecisionExtendedList;

    /**
     * Gets the value of the allotmentDecnExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.AllotmentDecnExtendedList }
     *     
     */
    public HAwardEventDecisionVO.AllotmentDecnExtendedList getAllotmentDecnExtendedList() {
        return allotmentDecnExtendedList;
    }

    /**
     * Sets the value of the allotmentDecnExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.AllotmentDecnExtendedList }
     *     
     */
    public void setAllotmentDecnExtendedList(HAwardEventDecisionVO.AllotmentDecnExtendedList value) {
        this.allotmentDecnExtendedList = value;
    }

    /**
     * Gets the value of the basicEligibilityDecisionList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.BasicEligibilityDecisionList }
     *     
     */
    public HAwardEventDecisionVO.BasicEligibilityDecisionList getBasicEligibilityDecisionList() {
        return basicEligibilityDecisionList;
    }

    /**
     * Sets the value of the basicEligibilityDecisionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.BasicEligibilityDecisionList }
     *     
     */
    public void setBasicEligibilityDecisionList(HAwardEventDecisionVO.BasicEligibilityDecisionList value) {
        this.basicEligibilityDecisionList = value;
    }

    /**
     * Gets the value of the burialBeneDecnList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.BurialBeneDecnList }
     *     
     */
    public HAwardEventDecisionVO.BurialBeneDecnList getBurialBeneDecnList() {
        return burialBeneDecnList;
    }

    /**
     * Sets the value of the burialBeneDecnList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.BurialBeneDecnList }
     *     
     */
    public void setBurialBeneDecnList(HAwardEventDecisionVO.BurialBeneDecnList value) {
        this.burialBeneDecnList = value;
    }

    /**
     * Gets the value of the burialBenefitDecnList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.BurialBenefitDecnList }
     *     
     */
    public HAwardEventDecisionVO.BurialBenefitDecnList getBurialBenefitDecnList() {
        return burialBenefitDecnList;
    }

    /**
     * Sets the value of the burialBenefitDecnList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.BurialBenefitDecnList }
     *     
     */
    public void setBurialBenefitDecnList(HAwardEventDecisionVO.BurialBenefitDecnList value) {
        this.burialBenefitDecnList = value;
    }

    /**
     * Gets the value of the burialSummaryDecnList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.BurialSummaryDecnList }
     *     
     */
    public HAwardEventDecisionVO.BurialSummaryDecnList getBurialSummaryDecnList() {
        return burialSummaryDecnList;
    }

    /**
     * Sets the value of the burialSummaryDecnList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.BurialSummaryDecnList }
     *     
     */
    public void setBurialSummaryDecnList(HAwardEventDecisionVO.BurialSummaryDecnList value) {
        this.burialSummaryDecnList = value;
    }

    /**
     * Gets the value of the clothingAllowanceDecnList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.ClothingAllowanceDecnList }
     *     
     */
    public HAwardEventDecisionVO.ClothingAllowanceDecnList getClothingAllowanceDecnList() {
        return clothingAllowanceDecnList;
    }

    /**
     * Sets the value of the clothingAllowanceDecnList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.ClothingAllowanceDecnList }
     *     
     */
    public void setClothingAllowanceDecnList(HAwardEventDecisionVO.ClothingAllowanceDecnList value) {
        this.clothingAllowanceDecnList = value;
    }

    /**
     * Gets the value of the dependencyDecisionList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.DependencyDecisionList }
     *     
     */
    public HAwardEventDecisionVO.DependencyDecisionList getDependencyDecisionList() {
        return dependencyDecisionList;
    }

    /**
     * Sets the value of the dependencyDecisionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.DependencyDecisionList }
     *     
     */
    public void setDependencyDecisionList(HAwardEventDecisionVO.DependencyDecisionList value) {
        this.dependencyDecisionList = value;
    }

    /**
     * Gets the value of the disabilityPayDecnExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.DisabilityPayDecnExtendedList }
     *     
     */
    public HAwardEventDecisionVO.DisabilityPayDecnExtendedList getDisabilityPayDecnExtendedList() {
        return disabilityPayDecnExtendedList;
    }

    /**
     * Sets the value of the disabilityPayDecnExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.DisabilityPayDecnExtendedList }
     *     
     */
    public void setDisabilityPayDecnExtendedList(HAwardEventDecisionVO.DisabilityPayDecnExtendedList value) {
        this.disabilityPayDecnExtendedList = value;
    }

    /**
     * Gets the value of the dischargePayList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.DischargePayList }
     *     
     */
    public HAwardEventDecisionVO.DischargePayList getDischargePayList() {
        return dischargePayList;
    }

    /**
     * Sets the value of the dischargePayList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.DischargePayList }
     *     
     */
    public void setDischargePayList(HAwardEventDecisionVO.DischargePayList value) {
        this.dischargePayList = value;
    }

    /**
     * Gets the value of the drillPayDecnList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.DrillPayDecnList }
     *     
     */
    public HAwardEventDecisionVO.DrillPayDecnList getDrillPayDecnList() {
        return drillPayDecnList;
    }

    /**
     * Sets the value of the drillPayDecnList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.DrillPayDecnList }
     *     
     */
    public void setDrillPayDecnList(HAwardEventDecisionVO.DrillPayDecnList value) {
        this.drillPayDecnList = value;
    }

    /**
     * Gets the value of the electionDecisionExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.ElectionDecisionExtendedList }
     *     
     */
    public HAwardEventDecisionVO.ElectionDecisionExtendedList getElectionDecisionExtendedList() {
        return electionDecisionExtendedList;
    }

    /**
     * Sets the value of the electionDecisionExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.ElectionDecisionExtendedList }
     *     
     */
    public void setElectionDecisionExtendedList(HAwardEventDecisionVO.ElectionDecisionExtendedList value) {
        this.electionDecisionExtendedList = value;
    }

    /**
     * Gets the value of the expenseDecisionExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.ExpenseDecisionExtendedList }
     *     
     */
    public HAwardEventDecisionVO.ExpenseDecisionExtendedList getExpenseDecisionExtendedList() {
        return expenseDecisionExtendedList;
    }

    /**
     * Sets the value of the expenseDecisionExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.ExpenseDecisionExtendedList }
     *     
     */
    public void setExpenseDecisionExtendedList(HAwardEventDecisionVO.ExpenseDecisionExtendedList value) {
        this.expenseDecisionExtendedList = value;
    }

    /**
     * Gets the value of the finclDecnCustomList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.FinclDecnCustomList }
     *     
     */
    public HAwardEventDecisionVO.FinclDecnCustomList getFinclDecnCustomList() {
        return finclDecnCustomList;
    }

    /**
     * Sets the value of the finclDecnCustomList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.FinclDecnCustomList }
     *     
     */
    public void setFinclDecnCustomList(HAwardEventDecisionVO.FinclDecnCustomList value) {
        this.finclDecnCustomList = value;
    }

    /**
     * Gets the value of the fraudDecisionExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.FraudDecisionExtendedList }
     *     
     */
    public HAwardEventDecisionVO.FraudDecisionExtendedList getFraudDecisionExtendedList() {
        return fraudDecisionExtendedList;
    }

    /**
     * Sets the value of the fraudDecisionExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.FraudDecisionExtendedList }
     *     
     */
    public void setFraudDecisionExtendedList(HAwardEventDecisionVO.FraudDecisionExtendedList value) {
        this.fraudDecisionExtendedList = value;
    }

    /**
     * Gets the value of the incomeDecisionExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.IncomeDecisionExtendedList }
     *     
     */
    public HAwardEventDecisionVO.IncomeDecisionExtendedList getIncomeDecisionExtendedList() {
        return incomeDecisionExtendedList;
    }

    /**
     * Sets the value of the incomeDecisionExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.IncomeDecisionExtendedList }
     *     
     */
    public void setIncomeDecisionExtendedList(HAwardEventDecisionVO.IncomeDecisionExtendedList value) {
        this.incomeDecisionExtendedList = value;
    }

    /**
     * Gets the value of the instznAdjustmentDecisionExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.InstznAdjustmentDecisionExtendedList }
     *     
     */
    public HAwardEventDecisionVO.InstznAdjustmentDecisionExtendedList getInstznAdjustmentDecisionExtendedList() {
        return instznAdjustmentDecisionExtendedList;
    }

    /**
     * Sets the value of the instznAdjustmentDecisionExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.InstznAdjustmentDecisionExtendedList }
     *     
     */
    public void setInstznAdjustmentDecisionExtendedList(HAwardEventDecisionVO.InstznAdjustmentDecisionExtendedList value) {
        this.instznAdjustmentDecisionExtendedList = value;
    }

    /**
     * Gets the value of the instznDecisionExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.InstznDecisionExtendedList }
     *     
     */
    public HAwardEventDecisionVO.InstznDecisionExtendedList getInstznDecisionExtendedList() {
        return instznDecisionExtendedList;
    }

    /**
     * Sets the value of the instznDecisionExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.InstznDecisionExtendedList }
     *     
     */
    public void setInstznDecisionExtendedList(HAwardEventDecisionVO.InstznDecisionExtendedList value) {
        this.instznDecisionExtendedList = value;
    }

    /**
     * Gets the value of the medalOfHonorDecnExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.MedalOfHonorDecnExtendedList }
     *     
     */
    public HAwardEventDecisionVO.MedalOfHonorDecnExtendedList getMedalOfHonorDecnExtendedList() {
        return medalOfHonorDecnExtendedList;
    }

    /**
     * Sets the value of the medalOfHonorDecnExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.MedalOfHonorDecnExtendedList }
     *     
     */
    public void setMedalOfHonorDecnExtendedList(HAwardEventDecisionVO.MedalOfHonorDecnExtendedList value) {
        this.medalOfHonorDecnExtendedList = value;
    }

    /**
     * Gets the value of the militaryEligibilityDecisionList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.MilitaryEligibilityDecisionList }
     *     
     */
    public HAwardEventDecisionVO.MilitaryEligibilityDecisionList getMilitaryEligibilityDecisionList() {
        return militaryEligibilityDecisionList;
    }

    /**
     * Sets the value of the militaryEligibilityDecisionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.MilitaryEligibilityDecisionList }
     *     
     */
    public void setMilitaryEligibilityDecisionList(HAwardEventDecisionVO.MilitaryEligibilityDecisionList value) {
        this.militaryEligibilityDecisionList = value;
    }

    /**
     * Gets the value of the netWorthDecisionExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.NetWorthDecisionExtendedList }
     *     
     */
    public HAwardEventDecisionVO.NetWorthDecisionExtendedList getNetWorthDecisionExtendedList() {
        return netWorthDecisionExtendedList;
    }

    /**
     * Sets the value of the netWorthDecisionExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.NetWorthDecisionExtendedList }
     *     
     */
    public void setNetWorthDecisionExtendedList(HAwardEventDecisionVO.NetWorthDecisionExtendedList value) {
        this.netWorthDecisionExtendedList = value;
    }

    /**
     * Gets the value of the otherWithholdingDecnExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.OtherWithholdingDecnExtendedList }
     *     
     */
    public HAwardEventDecisionVO.OtherWithholdingDecnExtendedList getOtherWithholdingDecnExtendedList() {
        return otherWithholdingDecnExtendedList;
    }

    /**
     * Sets the value of the otherWithholdingDecnExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.OtherWithholdingDecnExtendedList }
     *     
     */
    public void setOtherWithholdingDecnExtendedList(HAwardEventDecisionVO.OtherWithholdingDecnExtendedList value) {
        this.otherWithholdingDecnExtendedList = value;
    }

    /**
     * Gets the value of the payRateDecisionExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.PayRateDecisionExtendedList }
     *     
     */
    public HAwardEventDecisionVO.PayRateDecisionExtendedList getPayRateDecisionExtendedList() {
        return payRateDecisionExtendedList;
    }

    /**
     * Sets the value of the payRateDecisionExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.PayRateDecisionExtendedList }
     *     
     */
    public void setPayRateDecisionExtendedList(HAwardEventDecisionVO.PayRateDecisionExtendedList value) {
        this.payRateDecisionExtendedList = value;
    }

    /**
     * Gets the value of the retirementPayDecisionList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.RetirementPayDecisionList }
     *     
     */
    public HAwardEventDecisionVO.RetirementPayDecisionList getRetirementPayDecisionList() {
        return retirementPayDecisionList;
    }

    /**
     * Sets the value of the retirementPayDecisionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.RetirementPayDecisionList }
     *     
     */
    public void setRetirementPayDecisionList(HAwardEventDecisionVO.RetirementPayDecisionList value) {
        this.retirementPayDecisionList = value;
    }

    /**
     * Gets the value of the separationPayDecisionExtendedList property.
     * 
     * @return
     *     possible object is
     *     {@link HAwardEventDecisionVO.SeparationPayDecisionExtendedList }
     *     
     */
    public HAwardEventDecisionVO.SeparationPayDecisionExtendedList getSeparationPayDecisionExtendedList() {
        return separationPayDecisionExtendedList;
    }

    /**
     * Sets the value of the separationPayDecisionExtendedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAwardEventDecisionVO.SeparationPayDecisionExtendedList }
     *     
     */
    public void setSeparationPayDecisionExtendedList(HAwardEventDecisionVO.SeparationPayDecisionExtendedList value) {
        this.separationPayDecisionExtendedList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="allotmentDecnExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}allotmentDecnExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allotmentDecnExtendedVO"
    })
    public static class AllotmentDecnExtendedList {

        protected List<AllotmentDecnExtendedVO> allotmentDecnExtendedVO;

        /**
         * Gets the value of the allotmentDecnExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the allotmentDecnExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAllotmentDecnExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AllotmentDecnExtendedVO }
         * 
         * 
         */
        public List<AllotmentDecnExtendedVO> getAllotmentDecnExtendedVO() {
            if (allotmentDecnExtendedVO == null) {
                allotmentDecnExtendedVO = new ArrayList<AllotmentDecnExtendedVO>();
            }
            return this.allotmentDecnExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="basicEligibilityDecisionVO" type="{http://gov.va.vba.benefits.vbmsc/services}basicEligibilityDecisionVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "basicEligibilityDecisionVO"
    })
    public static class BasicEligibilityDecisionList {

        protected List<BasicEligibilityDecisionVO> basicEligibilityDecisionVO;

        /**
         * Gets the value of the basicEligibilityDecisionVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the basicEligibilityDecisionVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBasicEligibilityDecisionVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BasicEligibilityDecisionVO }
         * 
         * 
         */
        public List<BasicEligibilityDecisionVO> getBasicEligibilityDecisionVO() {
            if (basicEligibilityDecisionVO == null) {
                basicEligibilityDecisionVO = new ArrayList<BasicEligibilityDecisionVO>();
            }
            return this.basicEligibilityDecisionVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="burialBeneDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}burialBeneDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "burialBeneDecnVO"
    })
    public static class BurialBeneDecnList {

        protected List<BurialBeneDecnVO> burialBeneDecnVO;

        /**
         * Gets the value of the burialBeneDecnVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the burialBeneDecnVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBurialBeneDecnVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BurialBeneDecnVO }
         * 
         * 
         */
        public List<BurialBeneDecnVO> getBurialBeneDecnVO() {
            if (burialBeneDecnVO == null) {
                burialBeneDecnVO = new ArrayList<BurialBeneDecnVO>();
            }
            return this.burialBeneDecnVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="burialBenefitDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}burialBenefitDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "burialBenefitDecnVO"
    })
    public static class BurialBenefitDecnList {

        protected List<BurialBenefitDecnVO> burialBenefitDecnVO;

        /**
         * Gets the value of the burialBenefitDecnVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the burialBenefitDecnVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBurialBenefitDecnVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BurialBenefitDecnVO }
         * 
         * 
         */
        public List<BurialBenefitDecnVO> getBurialBenefitDecnVO() {
            if (burialBenefitDecnVO == null) {
                burialBenefitDecnVO = new ArrayList<BurialBenefitDecnVO>();
            }
            return this.burialBenefitDecnVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="burialSummaryDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}burialSummaryDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "burialSummaryDecnVO"
    })
    public static class BurialSummaryDecnList {

        protected List<BurialSummaryDecnVO> burialSummaryDecnVO;

        /**
         * Gets the value of the burialSummaryDecnVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the burialSummaryDecnVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBurialSummaryDecnVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BurialSummaryDecnVO }
         * 
         * 
         */
        public List<BurialSummaryDecnVO> getBurialSummaryDecnVO() {
            if (burialSummaryDecnVO == null) {
                burialSummaryDecnVO = new ArrayList<BurialSummaryDecnVO>();
            }
            return this.burialSummaryDecnVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="clothingAllowanceDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}clothingAllowanceDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clothingAllowanceDecnVO"
    })
    public static class ClothingAllowanceDecnList {

        protected List<ClothingAllowanceDecnVO> clothingAllowanceDecnVO;

        /**
         * Gets the value of the clothingAllowanceDecnVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the clothingAllowanceDecnVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClothingAllowanceDecnVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClothingAllowanceDecnVO }
         * 
         * 
         */
        public List<ClothingAllowanceDecnVO> getClothingAllowanceDecnVO() {
            if (clothingAllowanceDecnVO == null) {
                clothingAllowanceDecnVO = new ArrayList<ClothingAllowanceDecnVO>();
            }
            return this.clothingAllowanceDecnVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="dependencyDecisionVO" type="{http://gov.va.vba.benefits.vbmsc/services}dependencyDecisionVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dependencyDecisionVO"
    })
    public static class DependencyDecisionList {

        protected List<DependencyDecisionVO> dependencyDecisionVO;

        /**
         * Gets the value of the dependencyDecisionVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dependencyDecisionVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDependencyDecisionVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DependencyDecisionVO }
         * 
         * 
         */
        public List<DependencyDecisionVO> getDependencyDecisionVO() {
            if (dependencyDecisionVO == null) {
                dependencyDecisionVO = new ArrayList<DependencyDecisionVO>();
            }
            return this.dependencyDecisionVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="disabilityPayDecnExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}disabilityPayDecnExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "disabilityPayDecnExtendedVO"
    })
    public static class DisabilityPayDecnExtendedList {

        protected List<DisabilityPayDecnExtendedVO> disabilityPayDecnExtendedVO;

        /**
         * Gets the value of the disabilityPayDecnExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the disabilityPayDecnExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDisabilityPayDecnExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DisabilityPayDecnExtendedVO }
         * 
         * 
         */
        public List<DisabilityPayDecnExtendedVO> getDisabilityPayDecnExtendedVO() {
            if (disabilityPayDecnExtendedVO == null) {
                disabilityPayDecnExtendedVO = new ArrayList<DisabilityPayDecnExtendedVO>();
            }
            return this.disabilityPayDecnExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="dischargePayVO" type="{http://gov.va.vba.benefits.vbmsc/services}dischargePayVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dischargePayVO"
    })
    public static class DischargePayList {

        protected List<DischargePayVO> dischargePayVO;

        /**
         * Gets the value of the dischargePayVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dischargePayVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDischargePayVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DischargePayVO }
         * 
         * 
         */
        public List<DischargePayVO> getDischargePayVO() {
            if (dischargePayVO == null) {
                dischargePayVO = new ArrayList<DischargePayVO>();
            }
            return this.dischargePayVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="drillPayDecnVO" type="{http://gov.va.vba.benefits.vbmsc/services}drillPayDecnVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "drillPayDecnVO"
    })
    public static class DrillPayDecnList {

        protected List<DrillPayDecnVO> drillPayDecnVO;

        /**
         * Gets the value of the drillPayDecnVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the drillPayDecnVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDrillPayDecnVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DrillPayDecnVO }
         * 
         * 
         */
        public List<DrillPayDecnVO> getDrillPayDecnVO() {
            if (drillPayDecnVO == null) {
                drillPayDecnVO = new ArrayList<DrillPayDecnVO>();
            }
            return this.drillPayDecnVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="electionDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}electionDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "electionDecisionExtendedVO"
    })
    public static class ElectionDecisionExtendedList {

        protected List<ElectionDecisionExtendedVO> electionDecisionExtendedVO;

        /**
         * Gets the value of the electionDecisionExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the electionDecisionExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElectionDecisionExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ElectionDecisionExtendedVO }
         * 
         * 
         */
        public List<ElectionDecisionExtendedVO> getElectionDecisionExtendedVO() {
            if (electionDecisionExtendedVO == null) {
                electionDecisionExtendedVO = new ArrayList<ElectionDecisionExtendedVO>();
            }
            return this.electionDecisionExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="expenseDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}expenseDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "expenseDecisionExtendedVO"
    })
    public static class ExpenseDecisionExtendedList {

        protected List<ExpenseDecisionExtendedVO> expenseDecisionExtendedVO;

        /**
         * Gets the value of the expenseDecisionExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the expenseDecisionExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExpenseDecisionExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExpenseDecisionExtendedVO }
         * 
         * 
         */
        public List<ExpenseDecisionExtendedVO> getExpenseDecisionExtendedVO() {
            if (expenseDecisionExtendedVO == null) {
                expenseDecisionExtendedVO = new ArrayList<ExpenseDecisionExtendedVO>();
            }
            return this.expenseDecisionExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="finclDecnCustomVO" type="{http://gov.va.vba.benefits.vbmsc/services}finclDecnCustomVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "finclDecnCustomVO"
    })
    public static class FinclDecnCustomList {

        protected List<FinclDecnCustomVO> finclDecnCustomVO;

        /**
         * Gets the value of the finclDecnCustomVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the finclDecnCustomVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFinclDecnCustomVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FinclDecnCustomVO }
         * 
         * 
         */
        public List<FinclDecnCustomVO> getFinclDecnCustomVO() {
            if (finclDecnCustomVO == null) {
                finclDecnCustomVO = new ArrayList<FinclDecnCustomVO>();
            }
            return this.finclDecnCustomVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="fraudDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}fraudDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fraudDecisionExtendedVO"
    })
    public static class FraudDecisionExtendedList {

        protected List<FraudDecisionExtendedVO> fraudDecisionExtendedVO;

        /**
         * Gets the value of the fraudDecisionExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fraudDecisionExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFraudDecisionExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FraudDecisionExtendedVO }
         * 
         * 
         */
        public List<FraudDecisionExtendedVO> getFraudDecisionExtendedVO() {
            if (fraudDecisionExtendedVO == null) {
                fraudDecisionExtendedVO = new ArrayList<FraudDecisionExtendedVO>();
            }
            return this.fraudDecisionExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="incomeDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}incomeDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "incomeDecisionExtendedVO"
    })
    public static class IncomeDecisionExtendedList {

        protected List<IncomeDecisionExtendedVO> incomeDecisionExtendedVO;

        /**
         * Gets the value of the incomeDecisionExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the incomeDecisionExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncomeDecisionExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IncomeDecisionExtendedVO }
         * 
         * 
         */
        public List<IncomeDecisionExtendedVO> getIncomeDecisionExtendedVO() {
            if (incomeDecisionExtendedVO == null) {
                incomeDecisionExtendedVO = new ArrayList<IncomeDecisionExtendedVO>();
            }
            return this.incomeDecisionExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="instznAdjustmentDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}instznAdjustmentDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instznAdjustmentDecisionExtendedVO"
    })
    public static class InstznAdjustmentDecisionExtendedList {

        protected List<InstznAdjustmentDecisionExtendedVO> instznAdjustmentDecisionExtendedVO;

        /**
         * Gets the value of the instznAdjustmentDecisionExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the instznAdjustmentDecisionExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstznAdjustmentDecisionExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InstznAdjustmentDecisionExtendedVO }
         * 
         * 
         */
        public List<InstznAdjustmentDecisionExtendedVO> getInstznAdjustmentDecisionExtendedVO() {
            if (instznAdjustmentDecisionExtendedVO == null) {
                instznAdjustmentDecisionExtendedVO = new ArrayList<InstznAdjustmentDecisionExtendedVO>();
            }
            return this.instznAdjustmentDecisionExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="instznDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}instznDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instznDecisionExtendedVO"
    })
    public static class InstznDecisionExtendedList {

        protected List<InstznDecisionExtendedVO> instznDecisionExtendedVO;

        /**
         * Gets the value of the instznDecisionExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the instznDecisionExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstznDecisionExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InstznDecisionExtendedVO }
         * 
         * 
         */
        public List<InstznDecisionExtendedVO> getInstznDecisionExtendedVO() {
            if (instznDecisionExtendedVO == null) {
                instznDecisionExtendedVO = new ArrayList<InstznDecisionExtendedVO>();
            }
            return this.instznDecisionExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="medalOfHonorDecnExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}medalOfHonorDecnExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "medalOfHonorDecnExtendedVO"
    })
    public static class MedalOfHonorDecnExtendedList {

        protected List<MedalOfHonorDecnExtendedVO> medalOfHonorDecnExtendedVO;

        /**
         * Gets the value of the medalOfHonorDecnExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the medalOfHonorDecnExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMedalOfHonorDecnExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MedalOfHonorDecnExtendedVO }
         * 
         * 
         */
        public List<MedalOfHonorDecnExtendedVO> getMedalOfHonorDecnExtendedVO() {
            if (medalOfHonorDecnExtendedVO == null) {
                medalOfHonorDecnExtendedVO = new ArrayList<MedalOfHonorDecnExtendedVO>();
            }
            return this.medalOfHonorDecnExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="militaryEligibilityDecisionVO" type="{http://gov.va.vba.benefits.vbmsc/services}militaryEligibilityDecisionVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "militaryEligibilityDecisionVO"
    })
    public static class MilitaryEligibilityDecisionList {

        protected List<MilitaryEligibilityDecisionVO> militaryEligibilityDecisionVO;

        /**
         * Gets the value of the militaryEligibilityDecisionVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the militaryEligibilityDecisionVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMilitaryEligibilityDecisionVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MilitaryEligibilityDecisionVO }
         * 
         * 
         */
        public List<MilitaryEligibilityDecisionVO> getMilitaryEligibilityDecisionVO() {
            if (militaryEligibilityDecisionVO == null) {
                militaryEligibilityDecisionVO = new ArrayList<MilitaryEligibilityDecisionVO>();
            }
            return this.militaryEligibilityDecisionVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="netWorthDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}netWorthDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "netWorthDecisionExtendedVO"
    })
    public static class NetWorthDecisionExtendedList {

        protected List<NetWorthDecisionExtendedVO> netWorthDecisionExtendedVO;

        /**
         * Gets the value of the netWorthDecisionExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the netWorthDecisionExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNetWorthDecisionExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NetWorthDecisionExtendedVO }
         * 
         * 
         */
        public List<NetWorthDecisionExtendedVO> getNetWorthDecisionExtendedVO() {
            if (netWorthDecisionExtendedVO == null) {
                netWorthDecisionExtendedVO = new ArrayList<NetWorthDecisionExtendedVO>();
            }
            return this.netWorthDecisionExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="otherWithholdingDecnExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}otherWithholdingDecnExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "otherWithholdingDecnExtendedVO"
    })
    public static class OtherWithholdingDecnExtendedList {

        protected List<OtherWithholdingDecnExtendedVO> otherWithholdingDecnExtendedVO;

        /**
         * Gets the value of the otherWithholdingDecnExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the otherWithholdingDecnExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOtherWithholdingDecnExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OtherWithholdingDecnExtendedVO }
         * 
         * 
         */
        public List<OtherWithholdingDecnExtendedVO> getOtherWithholdingDecnExtendedVO() {
            if (otherWithholdingDecnExtendedVO == null) {
                otherWithholdingDecnExtendedVO = new ArrayList<OtherWithholdingDecnExtendedVO>();
            }
            return this.otherWithholdingDecnExtendedVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="payRateDecisionExtendedListVO" type="{http://gov.va.vba.benefits.vbmsc/services}payRateDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "payRateDecisionExtendedListVO"
    })
    public static class PayRateDecisionExtendedList {

        protected List<PayRateDecisionExtendedVO> payRateDecisionExtendedListVO;

        /**
         * Gets the value of the payRateDecisionExtendedListVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the payRateDecisionExtendedListVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPayRateDecisionExtendedListVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PayRateDecisionExtendedVO }
         * 
         * 
         */
        public List<PayRateDecisionExtendedVO> getPayRateDecisionExtendedListVO() {
            if (payRateDecisionExtendedListVO == null) {
                payRateDecisionExtendedListVO = new ArrayList<PayRateDecisionExtendedVO>();
            }
            return this.payRateDecisionExtendedListVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="retirementPayDecisionVO" type="{http://gov.va.vba.benefits.vbmsc/services}retirementPayDecisionVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "retirementPayDecisionVO"
    })
    public static class RetirementPayDecisionList {

        protected List<RetirementPayDecisionVO> retirementPayDecisionVO;

        /**
         * Gets the value of the retirementPayDecisionVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the retirementPayDecisionVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRetirementPayDecisionVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RetirementPayDecisionVO }
         * 
         * 
         */
        public List<RetirementPayDecisionVO> getRetirementPayDecisionVO() {
            if (retirementPayDecisionVO == null) {
                retirementPayDecisionVO = new ArrayList<RetirementPayDecisionVO>();
            }
            return this.retirementPayDecisionVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="separationPayDecisionExtendedVO" type="{http://gov.va.vba.benefits.vbmsc/services}separationPayDecisionExtendedVO" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "separationPayDecisionExtendedVO"
    })
    public static class SeparationPayDecisionExtendedList {

        protected List<SeparationPayDecisionExtendedVO> separationPayDecisionExtendedVO;

        /**
         * Gets the value of the separationPayDecisionExtendedVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the separationPayDecisionExtendedVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSeparationPayDecisionExtendedVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SeparationPayDecisionExtendedVO }
         * 
         * 
         */
        public List<SeparationPayDecisionExtendedVO> getSeparationPayDecisionExtendedVO() {
            if (separationPayDecisionExtendedVO == null) {
                separationPayDecisionExtendedVO = new ArrayList<SeparationPayDecisionExtendedVO>();
            }
            return this.separationPayDecisionExtendedVO;
        }

    }

}
