//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.11 at 09:35:49 AM EST 
//


package gov.va.vba.vbmsc.services.ws.client.mapping.awardData.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ratingSummaryVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ratingSummaryVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ratingApplicationUserID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ratingAwardSummaryID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="ratingPrintDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ratingProfileDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="rowInactivatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="veteranParticipantID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ratingSummaryVO", propOrder = {
    "ratingApplicationUserID",
    "ratingAwardSummaryID",
    "ratingPrintDate",
    "ratingProfileDate",
    "rowInactivatedDate",
    "veteranParticipantID"
})
@XmlSeeAlso({
    HRatingSummaryVO.class
})
public class RatingSummaryVO {

    protected String ratingApplicationUserID;
    protected Long ratingAwardSummaryID;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ratingPrintDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ratingProfileDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar rowInactivatedDate;
    protected Long veteranParticipantID;

    /**
     * Gets the value of the ratingApplicationUserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingApplicationUserID() {
        return ratingApplicationUserID;
    }

    /**
     * Sets the value of the ratingApplicationUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingApplicationUserID(String value) {
        this.ratingApplicationUserID = value;
    }

    /**
     * Gets the value of the ratingAwardSummaryID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRatingAwardSummaryID() {
        return ratingAwardSummaryID;
    }

    /**
     * Sets the value of the ratingAwardSummaryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRatingAwardSummaryID(Long value) {
        this.ratingAwardSummaryID = value;
    }

    /**
     * Gets the value of the ratingPrintDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRatingPrintDate() {
        return ratingPrintDate;
    }

    /**
     * Sets the value of the ratingPrintDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRatingPrintDate(XMLGregorianCalendar value) {
        this.ratingPrintDate = value;
    }

    /**
     * Gets the value of the ratingProfileDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRatingProfileDate() {
        return ratingProfileDate;
    }

    /**
     * Sets the value of the ratingProfileDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRatingProfileDate(XMLGregorianCalendar value) {
        this.ratingProfileDate = value;
    }

    /**
     * Gets the value of the rowInactivatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRowInactivatedDate() {
        return rowInactivatedDate;
    }

    /**
     * Sets the value of the rowInactivatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRowInactivatedDate(XMLGregorianCalendar value) {
        this.rowInactivatedDate = value;
    }

    /**
     * Gets the value of the veteranParticipantID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVeteranParticipantID() {
        return veteranParticipantID;
    }

    /**
     * Sets the value of the veteranParticipantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVeteranParticipantID(Long value) {
        this.veteranParticipantID = value;
    }

}
