//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.09 at 02:14:26 PM CDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.share.ratingComparison;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ratingComparisonServiceReturnVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ratingComparisonServiceReturnVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://session.ejb.awards.benefits.vba.va.gov/}voReturnBase">
 *       &lt;sequence>
 *         &lt;element name="anyRatingsWithinRangeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="combinedPercentCompareList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="combinedPercentCompare" type="{http://session.ejb.awards.benefits.vba.va.gov/}combinedPercentVO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="combinedPercentCurrentList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="combinedPercentCurrent" type="{http://session.ejb.awards.benefits.vba.va.gov/}combinedPercentVO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="differencesFound" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="earliestDependencyEligibilityDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="multipleRatingsFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prfilDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="promulgationDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ptcpntVetID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RatingDetails" type="{http://session.ejb.awards.benefits.vba.va.gov/}ratingDetailsVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rejectReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ratingProfileList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ratingProfile" type="{http://session.ejb.awards.benefits.vba.va.gov/}rbaPrfil" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ratingComparisonServiceReturnVO", propOrder = {
    "anyRatingsWithinRangeFlag",
    "combinedPercentCompareList",
    "combinedPercentCurrentList",
    "differencesFound",
    "earliestDependencyEligibilityDate",
    "multipleRatingsFlag",
    "prfilDt",
    "promulgationDt",
    "ptcpntVetID",
    "ratingDetails",
    "rejectReason",
    "ratingProfileList"
})
public class RatingComparisonServiceReturnVO
    extends VoReturnBase
{

    protected String anyRatingsWithinRangeFlag;
    protected RatingComparisonServiceReturnVO.CombinedPercentCompareList combinedPercentCompareList;
    protected RatingComparisonServiceReturnVO.CombinedPercentCurrentList combinedPercentCurrentList;
    protected String differencesFound;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar earliestDependencyEligibilityDate;
    protected String multipleRatingsFlag;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar prfilDt;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar promulgationDt;
    protected String ptcpntVetID;
    @XmlElement(name = "RatingDetails")
    protected List<RatingDetailsVO> ratingDetails;
    protected String rejectReason;
    protected RatingComparisonServiceReturnVO.RatingProfileList ratingProfileList;

    /**
     * Gets the value of the anyRatingsWithinRangeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnyRatingsWithinRangeFlag() {
        return anyRatingsWithinRangeFlag;
    }

    /**
     * Sets the value of the anyRatingsWithinRangeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnyRatingsWithinRangeFlag(String value) {
        this.anyRatingsWithinRangeFlag = value;
    }

    /**
     * Gets the value of the combinedPercentCompareList property.
     * 
     * @return
     *     possible object is
     *     {@link RatingComparisonServiceReturnVO.CombinedPercentCompareList }
     *     
     */
    public RatingComparisonServiceReturnVO.CombinedPercentCompareList getCombinedPercentCompareList() {
        return combinedPercentCompareList;
    }

    /**
     * Sets the value of the combinedPercentCompareList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingComparisonServiceReturnVO.CombinedPercentCompareList }
     *     
     */
    public void setCombinedPercentCompareList(RatingComparisonServiceReturnVO.CombinedPercentCompareList value) {
        this.combinedPercentCompareList = value;
    }

    /**
     * Gets the value of the combinedPercentCurrentList property.
     * 
     * @return
     *     possible object is
     *     {@link RatingComparisonServiceReturnVO.CombinedPercentCurrentList }
     *     
     */
    public RatingComparisonServiceReturnVO.CombinedPercentCurrentList getCombinedPercentCurrentList() {
        return combinedPercentCurrentList;
    }

    /**
     * Sets the value of the combinedPercentCurrentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingComparisonServiceReturnVO.CombinedPercentCurrentList }
     *     
     */
    public void setCombinedPercentCurrentList(RatingComparisonServiceReturnVO.CombinedPercentCurrentList value) {
        this.combinedPercentCurrentList = value;
    }

    /**
     * Gets the value of the differencesFound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDifferencesFound() {
        return differencesFound;
    }

    /**
     * Sets the value of the differencesFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDifferencesFound(String value) {
        this.differencesFound = value;
    }

    /**
     * Gets the value of the earliestDependencyEligibilityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEarliestDependencyEligibilityDate() {
        return earliestDependencyEligibilityDate;
    }

    /**
     * Sets the value of the earliestDependencyEligibilityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEarliestDependencyEligibilityDate(XMLGregorianCalendar value) {
        this.earliestDependencyEligibilityDate = value;
    }

    /**
     * Gets the value of the multipleRatingsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleRatingsFlag() {
        return multipleRatingsFlag;
    }

    /**
     * Sets the value of the multipleRatingsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleRatingsFlag(String value) {
        this.multipleRatingsFlag = value;
    }

    /**
     * Gets the value of the prfilDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrfilDt() {
        return prfilDt;
    }

    /**
     * Sets the value of the prfilDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPrfilDt(XMLGregorianCalendar value) {
        this.prfilDt = value;
    }

    /**
     * Gets the value of the promulgationDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPromulgationDt() {
        return promulgationDt;
    }

    /**
     * Sets the value of the promulgationDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPromulgationDt(XMLGregorianCalendar value) {
        this.promulgationDt = value;
    }

    /**
     * Gets the value of the ptcpntVetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtcpntVetID() {
        return ptcpntVetID;
    }

    /**
     * Sets the value of the ptcpntVetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtcpntVetID(String value) {
        this.ptcpntVetID = value;
    }

    /**
     * Gets the value of the ratingDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ratingDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRatingDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RatingDetailsVO }
     * 
     * 
     */
    public List<RatingDetailsVO> getRatingDetails() {
        if (ratingDetails == null) {
            ratingDetails = new ArrayList<RatingDetailsVO>();
        }
        return this.ratingDetails;
    }

    /**
     * Gets the value of the rejectReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * Sets the value of the rejectReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectReason(String value) {
        this.rejectReason = value;
    }

    /**
     * Gets the value of the ratingProfileList property.
     * 
     * @return
     *     possible object is
     *     {@link RatingComparisonServiceReturnVO.RatingProfileList }
     *     
     */
    public RatingComparisonServiceReturnVO.RatingProfileList getRatingProfileList() {
        return ratingProfileList;
    }

    /**
     * Sets the value of the ratingProfileList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingComparisonServiceReturnVO.RatingProfileList }
     *     
     */
    public void setRatingProfileList(RatingComparisonServiceReturnVO.RatingProfileList value) {
        this.ratingProfileList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="combinedPercentCompare" type="{http://session.ejb.awards.benefits.vba.va.gov/}combinedPercentVO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "combinedPercentCompare"
    })
    public static class CombinedPercentCompareList {

        protected List<CombinedPercentVO> combinedPercentCompare;

        /**
         * Gets the value of the combinedPercentCompare property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the combinedPercentCompare property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCombinedPercentCompare().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CombinedPercentVO }
         * 
         * 
         */
        public List<CombinedPercentVO> getCombinedPercentCompare() {
            if (combinedPercentCompare == null) {
                combinedPercentCompare = new ArrayList<CombinedPercentVO>();
            }
            return this.combinedPercentCompare;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="combinedPercentCurrent" type="{http://session.ejb.awards.benefits.vba.va.gov/}combinedPercentVO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "combinedPercentCurrent"
    })
    public static class CombinedPercentCurrentList {

        protected List<CombinedPercentVO> combinedPercentCurrent;

        /**
         * Gets the value of the combinedPercentCurrent property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the combinedPercentCurrent property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCombinedPercentCurrent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CombinedPercentVO }
         * 
         * 
         */
        public List<CombinedPercentVO> getCombinedPercentCurrent() {
            if (combinedPercentCurrent == null) {
                combinedPercentCurrent = new ArrayList<CombinedPercentVO>();
            }
            return this.combinedPercentCurrent;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ratingProfile" type="{http://session.ejb.awards.benefits.vba.va.gov/}rbaPrfil" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ratingProfile"
    })
    public static class RatingProfileList {

        protected List<RbaPrfil> ratingProfile;

        /**
         * Gets the value of the ratingProfile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ratingProfile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRatingProfile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RbaPrfil }
         * 
         * 
         */
        public List<RbaPrfil> getRatingProfile() {
            if (ratingProfile == null) {
                ratingProfile = new ArrayList<RbaPrfil>();
            }
            return this.ratingProfile;
        }

    }

}
