//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 09:22:05 AM CDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.vonapp.claimstatus;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.va.vba.rbps.services.ws.client.mapping.vonapp.status package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FindByPrimaryKeyResponse_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "findByPrimaryKeyResponse");
    private final static QName _FindAllAsArrayResponse_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "findAllAsArrayResponse");
    private final static QName _FaultException_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "FaultException");
    private final static QName _VnpProcRemoveResponse_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "vnpProcRemoveResponse");
    private final static QName _VnpProcUpdateResponse_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "vnpProcUpdateResponse");
    private final static QName _FindByPrimaryKey_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "findByPrimaryKey");
    private final static QName _VnpProcCreateResponse_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "vnpProcCreateResponse");
    private final static QName _MessageFaultException_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "MessageFaultException");
    private final static QName _FindAllAsArray_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "findAllAsArray");
    private final static QName _VnpProcCreate_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "vnpProcCreate");
    private final static QName _VnpProcRemove_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "vnpProcRemove");
    private final static QName _VnpProcUpdate_QNAME = new QName("http://procService.services.vonapp.vba.va.gov/", "vnpProcUpdate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.va.vba.rbps.services.ws.client.mapping.vonapp.status
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VnpProcCreateResponse }
     * 
     */
    public VnpProcCreateResponse createVnpProcCreateResponse() {
        return new VnpProcCreateResponse();
    }

    /**
     * Create an instance of {@link VnpProc }
     * 
     */
    public VnpProc createVnpProc() {
        return new VnpProc();
    }

    /**
     * Create an instance of {@link FindByPrimaryKey }
     * 
     */
    public FindByPrimaryKey createFindByPrimaryKey() {
        return new FindByPrimaryKey();
    }

    /**
     * Create an instance of {@link VnpProcUpdate }
     * 
     */
    public VnpProcUpdate createVnpProcUpdate() {
        return new VnpProcUpdate();
    }

    /**
     * Create an instance of {@link VnpProcUpdateResponse }
     * 
     */
    public VnpProcUpdateResponse createVnpProcUpdateResponse() {
        return new VnpProcUpdateResponse();
    }

    /**
     * Create an instance of {@link VnpProcRemoveResponse }
     * 
     */
    public VnpProcRemoveResponse createVnpProcRemoveResponse() {
        return new VnpProcRemoveResponse();
    }

    /**
     * Create an instance of {@link MessageFaultException }
     * 
     */
    public MessageFaultException createMessageFaultException() {
        return new MessageFaultException();
    }

    /**
     * Create an instance of {@link FindAllAsArrayResponse }
     * 
     */
    public FindAllAsArrayResponse createFindAllAsArrayResponse() {
        return new FindAllAsArrayResponse();
    }

    /**
     * Create an instance of {@link VnpProcRemove }
     * 
     */
    public VnpProcRemove createVnpProcRemove() {
        return new VnpProcRemove();
    }

    /**
     * Create an instance of {@link FindAllAsArray }
     * 
     */
    public FindAllAsArray createFindAllAsArray() {
        return new FindAllAsArray();
    }

    /**
     * Create an instance of {@link VnpProcDTO }
     * 
     */
    public VnpProcDTO createVnpProcDTO() {
        return new VnpProcDTO();
    }

    /**
     * Create an instance of {@link MessageFaultException.FaultExceptions }
     * 
     */
    public MessageFaultException.FaultExceptions createMessageFaultExceptionFaultExceptions() {
        return new MessageFaultException.FaultExceptions();
    }

    /**
     * Create an instance of {@link FindByPrimaryKeyResponse }
     * 
     */
    public FindByPrimaryKeyResponse createFindByPrimaryKeyResponse() {
        return new FindByPrimaryKeyResponse();
    }

    /**
     * Create an instance of {@link VnpProcCreate }
     * 
     */
    public VnpProcCreate createVnpProcCreate() {
        return new VnpProcCreate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindByPrimaryKeyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "findByPrimaryKeyResponse")
    public JAXBElement<FindByPrimaryKeyResponse> createFindByPrimaryKeyResponse(FindByPrimaryKeyResponse value) {
        return new JAXBElement<FindByPrimaryKeyResponse>(_FindByPrimaryKeyResponse_QNAME, FindByPrimaryKeyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAllAsArrayResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "findAllAsArrayResponse")
    public JAXBElement<FindAllAsArrayResponse> createFindAllAsArrayResponse(FindAllAsArrayResponse value) {
        return new JAXBElement<FindAllAsArrayResponse>(_FindAllAsArrayResponse_QNAME, FindAllAsArrayResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "FaultException")
    public JAXBElement<Object> createFaultException(Object value) {
        return new JAXBElement<Object>(_FaultException_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VnpProcRemoveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "vnpProcRemoveResponse")
    public JAXBElement<VnpProcRemoveResponse> createVnpProcRemoveResponse(VnpProcRemoveResponse value) {
        return new JAXBElement<VnpProcRemoveResponse>(_VnpProcRemoveResponse_QNAME, VnpProcRemoveResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VnpProcUpdateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "vnpProcUpdateResponse")
    public JAXBElement<VnpProcUpdateResponse> createVnpProcUpdateResponse(VnpProcUpdateResponse value) {
        return new JAXBElement<VnpProcUpdateResponse>(_VnpProcUpdateResponse_QNAME, VnpProcUpdateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindByPrimaryKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "findByPrimaryKey")
    public JAXBElement<FindByPrimaryKey> createFindByPrimaryKey(FindByPrimaryKey value) {
        return new JAXBElement<FindByPrimaryKey>(_FindByPrimaryKey_QNAME, FindByPrimaryKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VnpProcCreateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "vnpProcCreateResponse")
    public JAXBElement<VnpProcCreateResponse> createVnpProcCreateResponse(VnpProcCreateResponse value) {
        return new JAXBElement<VnpProcCreateResponse>(_VnpProcCreateResponse_QNAME, VnpProcCreateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageFaultException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "MessageFaultException")
    public JAXBElement<MessageFaultException> createMessageFaultException(MessageFaultException value) {
        return new JAXBElement<MessageFaultException>(_MessageFaultException_QNAME, MessageFaultException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAllAsArray }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "findAllAsArray")
    public JAXBElement<FindAllAsArray> createFindAllAsArray(FindAllAsArray value) {
        return new JAXBElement<FindAllAsArray>(_FindAllAsArray_QNAME, FindAllAsArray.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VnpProcCreate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "vnpProcCreate")
    public JAXBElement<VnpProcCreate> createVnpProcCreate(VnpProcCreate value) {
        return new JAXBElement<VnpProcCreate>(_VnpProcCreate_QNAME, VnpProcCreate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VnpProcRemove }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "vnpProcRemove")
    public JAXBElement<VnpProcRemove> createVnpProcRemove(VnpProcRemove value) {
        return new JAXBElement<VnpProcRemove>(_VnpProcRemove_QNAME, VnpProcRemove.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VnpProcUpdate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://procService.services.vonapp.vba.va.gov/", name = "vnpProcUpdate")
    public JAXBElement<VnpProcUpdate> createVnpProcUpdate(VnpProcUpdate value) {
        return new JAXBElement<VnpProcUpdate>(_VnpProcUpdate_QNAME, VnpProcUpdate.class, null, value);
    }

}
