//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.05 at 09:43:49 AM CDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.share.sojSignature;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.va.vba.rbps.services.ws.client.mapping.share.sojSignature package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FindClaimSuspnsReasons_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findClaimSuspnsReasons");
    private final static QName _FindStatesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findStatesResponse");
    private final static QName _FindEndProductTypes_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findEndProductTypes");
    private final static QName _FindForeignStates_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findForeignStates");
    private final static QName _FindBenefitClaimTypesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findBenefitClaimTypesResponse");
    private final static QName _FindBenefitClaimTypeIncrements_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findBenefitClaimTypeIncrements");
    private final static QName _FindUSStatesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findUSStatesResponse");
    private final static QName _FindCountriesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findCountriesResponse");
    private final static QName _FindBenefitClaimTypeIncrementsResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findBenefitClaimTypeIncrementsResponse");
    private final static QName _FindFlashesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findFlashesResponse");
    private final static QName _FindAllBenefitClaimTypesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findAllBenefitClaimTypesResponse");
    private final static QName _FindBenefitClaimTypes_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findBenefitClaimTypes");
    private final static QName _FindFlashes_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findFlashes");
    private final static QName _FindOtherMilitaryBranches_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findOtherMilitaryBranches");
    private final static QName _FindCountries_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findCountries");
    private final static QName _FindStates_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findStates");
    private final static QName _FindSignaturesByStationNumber_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findSignaturesByStationNumber");
    private final static QName _FindBenefitClaimLifeCycleStatuses_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findBenefitClaimLifeCycleStatuses");
    private final static QName _FindMilitaryBranches_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findMilitaryBranches");
    private final static QName _FindBenefitClaimLifeCycleStatusesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findBenefitClaimLifeCycleStatusesResponse");
    private final static QName _FindBenefitClaimTypeIncrementResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findBenefitClaimTypeIncrementResponse");
    private final static QName _FindSpecialIssues_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findSpecialIssues");
    private final static QName _FaultException_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "FaultException");
    private final static QName _FindClaimSuspnsReasonsResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findClaimSuspnsReasonsResponse");
    private final static QName _FindBenefitClaimTypeIncrement_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findBenefitClaimTypeIncrement");
    private final static QName _FindPayeeTypes_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findPayeeTypes");
    private final static QName _FindForeignStatesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findForeignStatesResponse");
    private final static QName _FindOtherMilitaryBranchesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findOtherMilitaryBranchesResponse");
    private final static QName _MessageFaultException_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "MessageFaultException");
    private final static QName _FindUSStates_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findUSStates");
    private final static QName _MessageException_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "MessageException");
    private final static QName _FindEndProductTypesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findEndProductTypesResponse");
    private final static QName _FindSpecialIssuesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findSpecialIssuesResponse");
    private final static QName _FindRegionalOfficesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findRegionalOfficesResponse");
    private final static QName _FindSignaturesByStationNumberResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findSignaturesByStationNumberResponse");
    private final static QName _FindAllBenefitClaimTypes_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findAllBenefitClaimTypes");
    private final static QName _FindStationsResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findStationsResponse");
    private final static QName _FindRegionalOffices_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findRegionalOffices");
    private final static QName _FindPayeeTypesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findPayeeTypesResponse");
    private final static QName _FindStations_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findStations");
    private final static QName _FindMilitaryBranchesResponse_QNAME = new QName("http://standarddata.services.vetsnet.vba.va.gov/", "findMilitaryBranchesResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.va.vba.rbps.services.ws.client.mapping.share.sojSignature
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TypeRlnshpDTO }
     * 
     */
    public TypeRlnshpDTO createTypeRlnshpDTO() {
        return new TypeRlnshpDTO();
    }

    /**
     * Create an instance of {@link FindForeignStatesResponse }
     * 
     */
    public FindForeignStatesResponse createFindForeignStatesResponse() {
        return new FindForeignStatesResponse();
    }

    /**
     * Create an instance of {@link FindBenefitClaimLifeCycleStatusesResponse }
     * 
     */
    public FindBenefitClaimLifeCycleStatusesResponse createFindBenefitClaimLifeCycleStatusesResponse() {
        return new FindBenefitClaimLifeCycleStatusesResponse();
    }

    /**
     * Create an instance of {@link ClaimSuspnsReasonDTO }
     * 
     */
    public ClaimSuspnsReasonDTO createClaimSuspnsReasonDTO() {
        return new ClaimSuspnsReasonDTO();
    }

    /**
     * Create an instance of {@link FindSignaturesByStationNumberResponse }
     * 
     */
    public FindSignaturesByStationNumberResponse createFindSignaturesByStationNumberResponse() {
        return new FindSignaturesByStationNumberResponse();
    }

    /**
     * Create an instance of {@link FindAllBenefitClaimTypesResponse }
     * 
     */
    public FindAllBenefitClaimTypesResponse createFindAllBenefitClaimTypesResponse() {
        return new FindAllBenefitClaimTypesResponse();
    }

    /**
     * Create an instance of {@link TypeDTO }
     * 
     */
    public TypeDTO createTypeDTO() {
        return new TypeDTO();
    }

    /**
     * Create an instance of {@link FindBenefitClaimTypeIncrementsResponse }
     * 
     */
    public FindBenefitClaimTypeIncrementsResponse createFindBenefitClaimTypeIncrementsResponse() {
        return new FindBenefitClaimTypeIncrementsResponse();
    }

    /**
     * Create an instance of {@link FindAllBenefitClaimTypes }
     * 
     */
    public FindAllBenefitClaimTypes createFindAllBenefitClaimTypes() {
        return new FindAllBenefitClaimTypes();
    }

    /**
     * Create an instance of {@link FindRegionalOffices }
     * 
     */
    public FindRegionalOffices createFindRegionalOffices() {
        return new FindRegionalOffices();
    }

    /**
     * Create an instance of {@link FindOtherMilitaryBranchesResponse }
     * 
     */
    public FindOtherMilitaryBranchesResponse createFindOtherMilitaryBranchesResponse() {
        return new FindOtherMilitaryBranchesResponse();
    }

    /**
     * Create an instance of {@link FindBenefitClaimTypesResponse }
     * 
     */
    public FindBenefitClaimTypesResponse createFindBenefitClaimTypesResponse() {
        return new FindBenefitClaimTypesResponse();
    }

    /**
     * Create an instance of {@link FindEndProductTypes }
     * 
     */
    public FindEndProductTypes createFindEndProductTypes() {
        return new FindEndProductTypes();
    }

    /**
     * Create an instance of {@link FindStationsResponse }
     * 
     */
    public FindStationsResponse createFindStationsResponse() {
        return new FindStationsResponse();
    }

    /**
     * Create an instance of {@link FindBenefitClaimLifeCycleStatuses }
     * 
     */
    public FindBenefitClaimLifeCycleStatuses createFindBenefitClaimLifeCycleStatuses() {
        return new FindBenefitClaimLifeCycleStatuses();
    }

    /**
     * Create an instance of {@link FindStatesResponse }
     * 
     */
    public FindStatesResponse createFindStatesResponse() {
        return new FindStatesResponse();
    }

    /**
     * Create an instance of {@link CntrlShareListValuesPK }
     * 
     */
    public CntrlShareListValuesPK createCntrlShareListValuesPK() {
        return new CntrlShareListValuesPK();
    }

    /**
     * Create an instance of {@link FindOtherMilitaryBranches }
     * 
     */
    public FindOtherMilitaryBranches createFindOtherMilitaryBranches() {
        return new FindOtherMilitaryBranches();
    }

    /**
     * Create an instance of {@link MessageFaultException }
     * 
     */
    public MessageFaultException createMessageFaultException() {
        return new MessageFaultException();
    }

    /**
     * Create an instance of {@link FindClaimSuspnsReasonsResponse }
     * 
     */
    public FindClaimSuspnsReasonsResponse createFindClaimSuspnsReasonsResponse() {
        return new FindClaimSuspnsReasonsResponse();
    }

    /**
     * Create an instance of {@link FindUSStatesResponse }
     * 
     */
    public FindUSStatesResponse createFindUSStatesResponse() {
        return new FindUSStatesResponse();
    }

    /**
     * Create an instance of {@link FindSpecialIssues }
     * 
     */
    public FindSpecialIssues createFindSpecialIssues() {
        return new FindSpecialIssues();
    }

    /**
     * Create an instance of {@link MessageFaultException.FaultExceptions }
     * 
     */
    public MessageFaultException.FaultExceptions createMessageFaultExceptionFaultExceptions() {
        return new MessageFaultException.FaultExceptions();
    }

    /**
     * Create an instance of {@link FindPayeeTypes }
     * 
     */
    public FindPayeeTypes createFindPayeeTypes() {
        return new FindPayeeTypes();
    }

    /**
     * Create an instance of {@link FindPayeeTypesResponse }
     * 
     */
    public FindPayeeTypesResponse createFindPayeeTypesResponse() {
        return new FindPayeeTypesResponse();
    }

    /**
     * Create an instance of {@link FindUSStates }
     * 
     */
    public FindUSStates createFindUSStates() {
        return new FindUSStates();
    }

    /**
     * Create an instance of {@link StnDTO }
     * 
     */
    public StnDTO createStnDTO() {
        return new StnDTO();
    }

    /**
     * Create an instance of {@link FindCountriesResponse }
     * 
     */
    public FindCountriesResponse createFindCountriesResponse() {
        return new FindCountriesResponse();
    }

    /**
     * Create an instance of {@link FindMilitaryBranches }
     * 
     */
    public FindMilitaryBranches createFindMilitaryBranches() {
        return new FindMilitaryBranches();
    }

    /**
     * Create an instance of {@link FindEndProductTypesResponse }
     * 
     */
    public FindEndProductTypesResponse createFindEndProductTypesResponse() {
        return new FindEndProductTypesResponse();
    }

    /**
     * Create an instance of {@link FindBenefitClaimTypeIncrements }
     * 
     */
    public FindBenefitClaimTypeIncrements createFindBenefitClaimTypeIncrements() {
        return new FindBenefitClaimTypeIncrements();
    }

    /**
     * Create an instance of {@link FindFlashesResponse }
     * 
     */
    public FindFlashesResponse createFindFlashesResponse() {
        return new FindFlashesResponse();
    }

    /**
     * Create an instance of {@link FindSignaturesByStationNumber }
     * 
     */
    public FindSignaturesByStationNumber createFindSignaturesByStationNumber() {
        return new FindSignaturesByStationNumber();
    }

    /**
     * Create an instance of {@link CntryTypeDTO }
     * 
     */
    public CntryTypeDTO createCntryTypeDTO() {
        return new CntryTypeDTO();
    }

    /**
     * Create an instance of {@link MessageFaultInfoBean }
     * 
     */
    public MessageFaultInfoBean createMessageFaultInfoBean() {
        return new MessageFaultInfoBean();
    }

    /**
     * Create an instance of {@link ListTypeDTO }
     * 
     */
    public ListTypeDTO createListTypeDTO() {
        return new ListTypeDTO();
    }

    /**
     * Create an instance of {@link FindBenefitClaimTypeIncrement }
     * 
     */
    public FindBenefitClaimTypeIncrement createFindBenefitClaimTypeIncrement() {
        return new FindBenefitClaimTypeIncrement();
    }

    /**
     * Create an instance of {@link StnPrfilDetailDTO }
     * 
     */
    public StnPrfilDetailDTO createStnPrfilDetailDTO() {
        return new StnPrfilDetailDTO();
    }

    /**
     * Create an instance of {@link FindBenefitClaimTypes }
     * 
     */
    public FindBenefitClaimTypes createFindBenefitClaimTypes() {
        return new FindBenefitClaimTypes();
    }

    /**
     * Create an instance of {@link FindBenefitClaimTypeIncrementResponse }
     * 
     */
    public FindBenefitClaimTypeIncrementResponse createFindBenefitClaimTypeIncrementResponse() {
        return new FindBenefitClaimTypeIncrementResponse();
    }

    /**
     * Create an instance of {@link FindSpecialIssuesResponse }
     * 
     */
    public FindSpecialIssuesResponse createFindSpecialIssuesResponse() {
        return new FindSpecialIssuesResponse();
    }

    /**
     * Create an instance of {@link FindClaimSuspnsReasons }
     * 
     */
    public FindClaimSuspnsReasons createFindClaimSuspnsReasons() {
        return new FindClaimSuspnsReasons();
    }

    /**
     * Create an instance of {@link FindForeignStates }
     * 
     */
    public FindForeignStates createFindForeignStates() {
        return new FindForeignStates();
    }

    /**
     * Create an instance of {@link TypePK }
     * 
     */
    public TypePK createTypePK() {
        return new TypePK();
    }

    /**
     * Create an instance of {@link FindCountries }
     * 
     */
    public FindCountries createFindCountries() {
        return new FindCountries();
    }

    /**
     * Create an instance of {@link FindFlashes }
     * 
     */
    public FindFlashes createFindFlashes() {
        return new FindFlashes();
    }

    /**
     * Create an instance of {@link FindStations }
     * 
     */
    public FindStations createFindStations() {
        return new FindStations();
    }

    /**
     * Create an instance of {@link FindStates }
     * 
     */
    public FindStates createFindStates() {
        return new FindStates();
    }

    /**
     * Create an instance of {@link FindMilitaryBranchesResponse }
     * 
     */
    public FindMilitaryBranchesResponse createFindMilitaryBranchesResponse() {
        return new FindMilitaryBranchesResponse();
    }

    /**
     * Create an instance of {@link StateDTO }
     * 
     */
    public StateDTO createStateDTO() {
        return new StateDTO();
    }

    /**
     * Create an instance of {@link FindRegionalOfficesResponse }
     * 
     */
    public FindRegionalOfficesResponse createFindRegionalOfficesResponse() {
        return new FindRegionalOfficesResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindClaimSuspnsReasons }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findClaimSuspnsReasons")
    public JAXBElement<FindClaimSuspnsReasons> createFindClaimSuspnsReasons(FindClaimSuspnsReasons value) {
        return new JAXBElement<FindClaimSuspnsReasons>(_FindClaimSuspnsReasons_QNAME, FindClaimSuspnsReasons.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindStatesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findStatesResponse")
    public JAXBElement<FindStatesResponse> createFindStatesResponse(FindStatesResponse value) {
        return new JAXBElement<FindStatesResponse>(_FindStatesResponse_QNAME, FindStatesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindEndProductTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findEndProductTypes")
    public JAXBElement<FindEndProductTypes> createFindEndProductTypes(FindEndProductTypes value) {
        return new JAXBElement<FindEndProductTypes>(_FindEndProductTypes_QNAME, FindEndProductTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindForeignStates }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findForeignStates")
    public JAXBElement<FindForeignStates> createFindForeignStates(FindForeignStates value) {
        return new JAXBElement<FindForeignStates>(_FindForeignStates_QNAME, FindForeignStates.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindBenefitClaimTypesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findBenefitClaimTypesResponse")
    public JAXBElement<FindBenefitClaimTypesResponse> createFindBenefitClaimTypesResponse(FindBenefitClaimTypesResponse value) {
        return new JAXBElement<FindBenefitClaimTypesResponse>(_FindBenefitClaimTypesResponse_QNAME, FindBenefitClaimTypesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindBenefitClaimTypeIncrements }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findBenefitClaimTypeIncrements")
    public JAXBElement<FindBenefitClaimTypeIncrements> createFindBenefitClaimTypeIncrements(FindBenefitClaimTypeIncrements value) {
        return new JAXBElement<FindBenefitClaimTypeIncrements>(_FindBenefitClaimTypeIncrements_QNAME, FindBenefitClaimTypeIncrements.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindUSStatesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findUSStatesResponse")
    public JAXBElement<FindUSStatesResponse> createFindUSStatesResponse(FindUSStatesResponse value) {
        return new JAXBElement<FindUSStatesResponse>(_FindUSStatesResponse_QNAME, FindUSStatesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindCountriesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findCountriesResponse")
    public JAXBElement<FindCountriesResponse> createFindCountriesResponse(FindCountriesResponse value) {
        return new JAXBElement<FindCountriesResponse>(_FindCountriesResponse_QNAME, FindCountriesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindBenefitClaimTypeIncrementsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findBenefitClaimTypeIncrementsResponse")
    public JAXBElement<FindBenefitClaimTypeIncrementsResponse> createFindBenefitClaimTypeIncrementsResponse(FindBenefitClaimTypeIncrementsResponse value) {
        return new JAXBElement<FindBenefitClaimTypeIncrementsResponse>(_FindBenefitClaimTypeIncrementsResponse_QNAME, FindBenefitClaimTypeIncrementsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindFlashesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findFlashesResponse")
    public JAXBElement<FindFlashesResponse> createFindFlashesResponse(FindFlashesResponse value) {
        return new JAXBElement<FindFlashesResponse>(_FindFlashesResponse_QNAME, FindFlashesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAllBenefitClaimTypesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findAllBenefitClaimTypesResponse")
    public JAXBElement<FindAllBenefitClaimTypesResponse> createFindAllBenefitClaimTypesResponse(FindAllBenefitClaimTypesResponse value) {
        return new JAXBElement<FindAllBenefitClaimTypesResponse>(_FindAllBenefitClaimTypesResponse_QNAME, FindAllBenefitClaimTypesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindBenefitClaimTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findBenefitClaimTypes")
    public JAXBElement<FindBenefitClaimTypes> createFindBenefitClaimTypes(FindBenefitClaimTypes value) {
        return new JAXBElement<FindBenefitClaimTypes>(_FindBenefitClaimTypes_QNAME, FindBenefitClaimTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindFlashes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findFlashes")
    public JAXBElement<FindFlashes> createFindFlashes(FindFlashes value) {
        return new JAXBElement<FindFlashes>(_FindFlashes_QNAME, FindFlashes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindOtherMilitaryBranches }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findOtherMilitaryBranches")
    public JAXBElement<FindOtherMilitaryBranches> createFindOtherMilitaryBranches(FindOtherMilitaryBranches value) {
        return new JAXBElement<FindOtherMilitaryBranches>(_FindOtherMilitaryBranches_QNAME, FindOtherMilitaryBranches.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindCountries }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findCountries")
    public JAXBElement<FindCountries> createFindCountries(FindCountries value) {
        return new JAXBElement<FindCountries>(_FindCountries_QNAME, FindCountries.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindStates }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findStates")
    public JAXBElement<FindStates> createFindStates(FindStates value) {
        return new JAXBElement<FindStates>(_FindStates_QNAME, FindStates.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindSignaturesByStationNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findSignaturesByStationNumber")
    public JAXBElement<FindSignaturesByStationNumber> createFindSignaturesByStationNumber(FindSignaturesByStationNumber value) {
        return new JAXBElement<FindSignaturesByStationNumber>(_FindSignaturesByStationNumber_QNAME, FindSignaturesByStationNumber.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindBenefitClaimLifeCycleStatuses }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findBenefitClaimLifeCycleStatuses")
    public JAXBElement<FindBenefitClaimLifeCycleStatuses> createFindBenefitClaimLifeCycleStatuses(FindBenefitClaimLifeCycleStatuses value) {
        return new JAXBElement<FindBenefitClaimLifeCycleStatuses>(_FindBenefitClaimLifeCycleStatuses_QNAME, FindBenefitClaimLifeCycleStatuses.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindMilitaryBranches }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findMilitaryBranches")
    public JAXBElement<FindMilitaryBranches> createFindMilitaryBranches(FindMilitaryBranches value) {
        return new JAXBElement<FindMilitaryBranches>(_FindMilitaryBranches_QNAME, FindMilitaryBranches.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindBenefitClaimLifeCycleStatusesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findBenefitClaimLifeCycleStatusesResponse")
    public JAXBElement<FindBenefitClaimLifeCycleStatusesResponse> createFindBenefitClaimLifeCycleStatusesResponse(FindBenefitClaimLifeCycleStatusesResponse value) {
        return new JAXBElement<FindBenefitClaimLifeCycleStatusesResponse>(_FindBenefitClaimLifeCycleStatusesResponse_QNAME, FindBenefitClaimLifeCycleStatusesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindBenefitClaimTypeIncrementResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findBenefitClaimTypeIncrementResponse")
    public JAXBElement<FindBenefitClaimTypeIncrementResponse> createFindBenefitClaimTypeIncrementResponse(FindBenefitClaimTypeIncrementResponse value) {
        return new JAXBElement<FindBenefitClaimTypeIncrementResponse>(_FindBenefitClaimTypeIncrementResponse_QNAME, FindBenefitClaimTypeIncrementResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindSpecialIssues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findSpecialIssues")
    public JAXBElement<FindSpecialIssues> createFindSpecialIssues(FindSpecialIssues value) {
        return new JAXBElement<FindSpecialIssues>(_FindSpecialIssues_QNAME, FindSpecialIssues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "FaultException")
    public JAXBElement<Object> createFaultException(Object value) {
        return new JAXBElement<Object>(_FaultException_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindClaimSuspnsReasonsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findClaimSuspnsReasonsResponse")
    public JAXBElement<FindClaimSuspnsReasonsResponse> createFindClaimSuspnsReasonsResponse(FindClaimSuspnsReasonsResponse value) {
        return new JAXBElement<FindClaimSuspnsReasonsResponse>(_FindClaimSuspnsReasonsResponse_QNAME, FindClaimSuspnsReasonsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindBenefitClaimTypeIncrement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findBenefitClaimTypeIncrement")
    public JAXBElement<FindBenefitClaimTypeIncrement> createFindBenefitClaimTypeIncrement(FindBenefitClaimTypeIncrement value) {
        return new JAXBElement<FindBenefitClaimTypeIncrement>(_FindBenefitClaimTypeIncrement_QNAME, FindBenefitClaimTypeIncrement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindPayeeTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findPayeeTypes")
    public JAXBElement<FindPayeeTypes> createFindPayeeTypes(FindPayeeTypes value) {
        return new JAXBElement<FindPayeeTypes>(_FindPayeeTypes_QNAME, FindPayeeTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindForeignStatesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findForeignStatesResponse")
    public JAXBElement<FindForeignStatesResponse> createFindForeignStatesResponse(FindForeignStatesResponse value) {
        return new JAXBElement<FindForeignStatesResponse>(_FindForeignStatesResponse_QNAME, FindForeignStatesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindOtherMilitaryBranchesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findOtherMilitaryBranchesResponse")
    public JAXBElement<FindOtherMilitaryBranchesResponse> createFindOtherMilitaryBranchesResponse(FindOtherMilitaryBranchesResponse value) {
        return new JAXBElement<FindOtherMilitaryBranchesResponse>(_FindOtherMilitaryBranchesResponse_QNAME, FindOtherMilitaryBranchesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageFaultException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "MessageFaultException")
    public JAXBElement<MessageFaultException> createMessageFaultException(MessageFaultException value) {
        return new JAXBElement<MessageFaultException>(_MessageFaultException_QNAME, MessageFaultException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindUSStates }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findUSStates")
    public JAXBElement<FindUSStates> createFindUSStates(FindUSStates value) {
        return new JAXBElement<FindUSStates>(_FindUSStates_QNAME, FindUSStates.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageFaultInfoBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "MessageException")
    public JAXBElement<MessageFaultInfoBean> createMessageException(MessageFaultInfoBean value) {
        return new JAXBElement<MessageFaultInfoBean>(_MessageException_QNAME, MessageFaultInfoBean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindEndProductTypesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findEndProductTypesResponse")
    public JAXBElement<FindEndProductTypesResponse> createFindEndProductTypesResponse(FindEndProductTypesResponse value) {
        return new JAXBElement<FindEndProductTypesResponse>(_FindEndProductTypesResponse_QNAME, FindEndProductTypesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindSpecialIssuesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findSpecialIssuesResponse")
    public JAXBElement<FindSpecialIssuesResponse> createFindSpecialIssuesResponse(FindSpecialIssuesResponse value) {
        return new JAXBElement<FindSpecialIssuesResponse>(_FindSpecialIssuesResponse_QNAME, FindSpecialIssuesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindRegionalOfficesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findRegionalOfficesResponse")
    public JAXBElement<FindRegionalOfficesResponse> createFindRegionalOfficesResponse(FindRegionalOfficesResponse value) {
        return new JAXBElement<FindRegionalOfficesResponse>(_FindRegionalOfficesResponse_QNAME, FindRegionalOfficesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindSignaturesByStationNumberResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findSignaturesByStationNumberResponse")
    public JAXBElement<FindSignaturesByStationNumberResponse> createFindSignaturesByStationNumberResponse(FindSignaturesByStationNumberResponse value) {
        return new JAXBElement<FindSignaturesByStationNumberResponse>(_FindSignaturesByStationNumberResponse_QNAME, FindSignaturesByStationNumberResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAllBenefitClaimTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findAllBenefitClaimTypes")
    public JAXBElement<FindAllBenefitClaimTypes> createFindAllBenefitClaimTypes(FindAllBenefitClaimTypes value) {
        return new JAXBElement<FindAllBenefitClaimTypes>(_FindAllBenefitClaimTypes_QNAME, FindAllBenefitClaimTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindStationsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findStationsResponse")
    public JAXBElement<FindStationsResponse> createFindStationsResponse(FindStationsResponse value) {
        return new JAXBElement<FindStationsResponse>(_FindStationsResponse_QNAME, FindStationsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindRegionalOffices }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findRegionalOffices")
    public JAXBElement<FindRegionalOffices> createFindRegionalOffices(FindRegionalOffices value) {
        return new JAXBElement<FindRegionalOffices>(_FindRegionalOffices_QNAME, FindRegionalOffices.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindPayeeTypesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findPayeeTypesResponse")
    public JAXBElement<FindPayeeTypesResponse> createFindPayeeTypesResponse(FindPayeeTypesResponse value) {
        return new JAXBElement<FindPayeeTypesResponse>(_FindPayeeTypesResponse_QNAME, FindPayeeTypesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindStations }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findStations")
    public JAXBElement<FindStations> createFindStations(FindStations value) {
        return new JAXBElement<FindStations>(_FindStations_QNAME, FindStations.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindMilitaryBranchesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standarddata.services.vetsnet.vba.va.gov/", name = "findMilitaryBranchesResponse")
    public JAXBElement<FindMilitaryBranchesResponse> createFindMilitaryBranchesResponse(FindMilitaryBranchesResponse value) {
        return new JAXBElement<FindMilitaryBranchesResponse>(_FindMilitaryBranchesResponse_QNAME, FindMilitaryBranchesResponse.class, null, value);
    }

}
