//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 04:22:29 PM CDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.awards.personService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ptcpntRlnshpPK complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ptcpntRlnshpPK">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fiduciaryInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ptcpntIdA" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ptcpntIdB" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ptcpntRlnshpTypeNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ptcpntRlnshpPK", propOrder = {
    "fiduciaryInd",
    "ptcpntIdA",
    "ptcpntIdB",
    "ptcpntRlnshpTypeNm"
})
public class PtcpntRlnshpPK {

    protected String fiduciaryInd;
    protected Long ptcpntIdA;
    protected Long ptcpntIdB;
    protected String ptcpntRlnshpTypeNm;

    /**
     * Gets the value of the fiduciaryInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiduciaryInd() {
        return fiduciaryInd;
    }

    /**
     * Sets the value of the fiduciaryInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiduciaryInd(String value) {
        this.fiduciaryInd = value;
    }

    /**
     * Gets the value of the ptcpntIdA property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPtcpntIdA() {
        return ptcpntIdA;
    }

    /**
     * Sets the value of the ptcpntIdA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPtcpntIdA(Long value) {
        this.ptcpntIdA = value;
    }

    /**
     * Gets the value of the ptcpntIdB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPtcpntIdB() {
        return ptcpntIdB;
    }

    /**
     * Sets the value of the ptcpntIdB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPtcpntIdB(Long value) {
        this.ptcpntIdB = value;
    }

    /**
     * Gets the value of the ptcpntRlnshpTypeNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtcpntRlnshpTypeNm() {
        return ptcpntRlnshpTypeNm;
    }

    /**
     * Sets the value of the ptcpntRlnshpTypeNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtcpntRlnshpTypeNm(String value) {
        this.ptcpntRlnshpTypeNm = value;
    }

}
