//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.24 at 04:39:54 PM CDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.share.familytree;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flashUpdateInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flashUpdateInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flashes" type="{http://services.share.benefits.vba.va.gov/}flash" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="numberOfFlashes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ptcpntID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flashUpdateInput", propOrder = {
    "flashes",
    "numberOfFlashes",
    "ptcpntID"
})
public class FlashUpdateInput {

    @XmlElement(nillable = true)
    protected List<Flash> flashes;
    protected String numberOfFlashes;
    protected String ptcpntID;

    /**
     * Gets the value of the flashes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flashes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlashes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Flash }
     * 
     * 
     */
    public List<Flash> getFlashes() {
        if (flashes == null) {
            flashes = new ArrayList<Flash>();
        }
        return this.flashes;
    }

    /**
     * Gets the value of the numberOfFlashes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfFlashes() {
        return numberOfFlashes;
    }

    /**
     * Sets the value of the numberOfFlashes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfFlashes(String value) {
        this.numberOfFlashes = value;
    }

    /**
     * Gets the value of the ptcpntID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtcpntID() {
        return ptcpntID;
    }

    /**
     * Sets the value of the ptcpntID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtcpntID(String value) {
        this.ptcpntID = value;
    }

}
