//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.24 at 04:39:54 PM CDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.share.familytree;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for incomeSummaryRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="incomeSummaryRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="awardTypeCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="expenseRecords" type="{http://services.share.benefits.vba.va.gov/}expenseRecord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="familyIncomeInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="familyNetWorthAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="incomeRecords" type="{http://services.share.benefits.vba.va.gov/}incomeRecord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ivap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ivmAdjustmentInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="netWorthInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberOfExpenseRecords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberOfIncomeRecords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="potentialFraudInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ptcpntBeneId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ptcpntVetId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="returnCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="returnMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "incomeSummaryRecord", propOrder = {
    "awardTypeCd",
    "effectiveDate",
    "expenseRecords",
    "familyIncomeInd",
    "familyNetWorthAmount",
    "incomeRecords",
    "ivap",
    "ivmAdjustmentInd",
    "netWorthInd",
    "numberOfExpenseRecords",
    "numberOfIncomeRecords",
    "potentialFraudInd",
    "ptcpntBeneId",
    "ptcpntVetId",
    "returnCode",
    "returnMessage"
})
public class IncomeSummaryRecord {

    protected String awardTypeCd;
    protected String effectiveDate;
    @XmlElement(nillable = true)
    protected List<ExpenseRecord> expenseRecords;
    protected String familyIncomeInd;
    protected String familyNetWorthAmount;
    @XmlElement(nillable = true)
    protected List<IncomeRecord> incomeRecords;
    protected String ivap;
    protected String ivmAdjustmentInd;
    protected String netWorthInd;
    protected String numberOfExpenseRecords;
    protected String numberOfIncomeRecords;
    protected String potentialFraudInd;
    protected String ptcpntBeneId;
    protected String ptcpntVetId;
    protected String returnCode;
    protected String returnMessage;

    /**
     * Gets the value of the awardTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardTypeCd() {
        return awardTypeCd;
    }

    /**
     * Sets the value of the awardTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardTypeCd(String value) {
        this.awardTypeCd = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expenseRecords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expenseRecords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpenseRecords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpenseRecord }
     * 
     * 
     */
    public List<ExpenseRecord> getExpenseRecords() {
        if (expenseRecords == null) {
            expenseRecords = new ArrayList<ExpenseRecord>();
        }
        return this.expenseRecords;
    }

    /**
     * Gets the value of the familyIncomeInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyIncomeInd() {
        return familyIncomeInd;
    }

    /**
     * Sets the value of the familyIncomeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyIncomeInd(String value) {
        this.familyIncomeInd = value;
    }

    /**
     * Gets the value of the familyNetWorthAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyNetWorthAmount() {
        return familyNetWorthAmount;
    }

    /**
     * Sets the value of the familyNetWorthAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyNetWorthAmount(String value) {
        this.familyNetWorthAmount = value;
    }

    /**
     * Gets the value of the incomeRecords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incomeRecords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncomeRecords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncomeRecord }
     * 
     * 
     */
    public List<IncomeRecord> getIncomeRecords() {
        if (incomeRecords == null) {
            incomeRecords = new ArrayList<IncomeRecord>();
        }
        return this.incomeRecords;
    }

    /**
     * Gets the value of the ivap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIvap() {
        return ivap;
    }

    /**
     * Sets the value of the ivap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIvap(String value) {
        this.ivap = value;
    }

    /**
     * Gets the value of the ivmAdjustmentInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIvmAdjustmentInd() {
        return ivmAdjustmentInd;
    }

    /**
     * Sets the value of the ivmAdjustmentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIvmAdjustmentInd(String value) {
        this.ivmAdjustmentInd = value;
    }

    /**
     * Gets the value of the netWorthInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetWorthInd() {
        return netWorthInd;
    }

    /**
     * Sets the value of the netWorthInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetWorthInd(String value) {
        this.netWorthInd = value;
    }

    /**
     * Gets the value of the numberOfExpenseRecords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfExpenseRecords() {
        return numberOfExpenseRecords;
    }

    /**
     * Sets the value of the numberOfExpenseRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfExpenseRecords(String value) {
        this.numberOfExpenseRecords = value;
    }

    /**
     * Gets the value of the numberOfIncomeRecords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfIncomeRecords() {
        return numberOfIncomeRecords;
    }

    /**
     * Sets the value of the numberOfIncomeRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfIncomeRecords(String value) {
        this.numberOfIncomeRecords = value;
    }

    /**
     * Gets the value of the potentialFraudInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotentialFraudInd() {
        return potentialFraudInd;
    }

    /**
     * Sets the value of the potentialFraudInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotentialFraudInd(String value) {
        this.potentialFraudInd = value;
    }

    /**
     * Gets the value of the ptcpntBeneId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtcpntBeneId() {
        return ptcpntBeneId;
    }

    /**
     * Sets the value of the ptcpntBeneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtcpntBeneId(String value) {
        this.ptcpntBeneId = value;
    }

    /**
     * Gets the value of the ptcpntVetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtcpntVetId() {
        return ptcpntVetId;
    }

    /**
     * Sets the value of the ptcpntVetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtcpntVetId(String value) {
        this.ptcpntVetId = value;
    }

    /**
     * Gets the value of the returnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * Sets the value of the returnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnCode(String value) {
        this.returnCode = value;
    }

    /**
     * Gets the value of the returnMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnMessage() {
        return returnMessage;
    }

    /**
     * Sets the value of the returnMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnMessage(String value) {
        this.returnMessage = value;
    }

}
