//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 04:43:13 PM CDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.awards.service;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for awardEventVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="awardEventVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://gov.va.vba.benefits.awards.ws/services}voBase">
 *       &lt;sequence>
 *         &lt;element name="awardEventID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="awardEventType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="awardGenerationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="awardOverrideIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="awardPrintRemarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="awardType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="beneficiaryID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="concurrentRetirementDisabilityPayIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="controlDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="firstChangedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="generationBatchType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="generationProcessType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modifiedAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modifiedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="modifiedLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modifiedProcess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processingStationLocationID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ratingAwardSummaryID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stationOfJurisdictionLocationID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="totalNetAmountDue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="veteranID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "awardEventVO", propOrder = {
    "awardEventID",
    "awardEventType",
    "awardGenerationDate",
    "awardOverrideIndicator",
    "awardPrintRemarks",
    "awardType",
    "beneficiaryID",
    "concurrentRetirementDisabilityPayIndicator",
    "controlDate",
    "firstChangedDate",
    "generationBatchType",
    "generationProcessType",
    "modifiedAction",
    "modifiedBy",
    "modifiedDate",
    "modifiedLocation",
    "modifiedProcess",
    "processingStationLocationID",
    "ratingAwardSummaryID",
    "remarks",
    "stationOfJurisdictionLocationID",
    "totalNetAmountDue",
    "veteranID"
})
@XmlSeeAlso({
    HAwardEventVO.class
})
public class AwardEventVO
    extends VoBase
{

    protected Long awardEventID;
    protected String awardEventType;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar awardGenerationDate;
    protected String awardOverrideIndicator;
    protected String awardPrintRemarks;
    protected String awardType;
    protected Long beneficiaryID;
    protected String concurrentRetirementDisabilityPayIndicator;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar controlDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar firstChangedDate;
    protected String generationBatchType;
    protected String generationProcessType;
    protected String modifiedAction;
    protected String modifiedBy;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifiedDate;
    protected String modifiedLocation;
    protected String modifiedProcess;
    protected Long processingStationLocationID;
    protected Long ratingAwardSummaryID;
    protected String remarks;
    protected Long stationOfJurisdictionLocationID;
    protected BigDecimal totalNetAmountDue;
    protected Long veteranID;

    /**
     * Gets the value of the awardEventID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAwardEventID() {
        return awardEventID;
    }

    /**
     * Sets the value of the awardEventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAwardEventID(Long value) {
        this.awardEventID = value;
    }

    /**
     * Gets the value of the awardEventType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardEventType() {
        return awardEventType;
    }

    /**
     * Sets the value of the awardEventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardEventType(String value) {
        this.awardEventType = value;
    }

    /**
     * Gets the value of the awardGenerationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAwardGenerationDate() {
        return awardGenerationDate;
    }

    /**
     * Sets the value of the awardGenerationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAwardGenerationDate(XMLGregorianCalendar value) {
        this.awardGenerationDate = value;
    }

    /**
     * Gets the value of the awardOverrideIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardOverrideIndicator() {
        return awardOverrideIndicator;
    }

    /**
     * Sets the value of the awardOverrideIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardOverrideIndicator(String value) {
        this.awardOverrideIndicator = value;
    }

    /**
     * Gets the value of the awardPrintRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardPrintRemarks() {
        return awardPrintRemarks;
    }

    /**
     * Sets the value of the awardPrintRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardPrintRemarks(String value) {
        this.awardPrintRemarks = value;
    }

    /**
     * Gets the value of the awardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardType() {
        return awardType;
    }

    /**
     * Sets the value of the awardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardType(String value) {
        this.awardType = value;
    }

    /**
     * Gets the value of the beneficiaryID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBeneficiaryID() {
        return beneficiaryID;
    }

    /**
     * Sets the value of the beneficiaryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBeneficiaryID(Long value) {
        this.beneficiaryID = value;
    }

    /**
     * Gets the value of the concurrentRetirementDisabilityPayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcurrentRetirementDisabilityPayIndicator() {
        return concurrentRetirementDisabilityPayIndicator;
    }

    /**
     * Sets the value of the concurrentRetirementDisabilityPayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcurrentRetirementDisabilityPayIndicator(String value) {
        this.concurrentRetirementDisabilityPayIndicator = value;
    }

    /**
     * Gets the value of the controlDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getControlDate() {
        return controlDate;
    }

    /**
     * Sets the value of the controlDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setControlDate(XMLGregorianCalendar value) {
        this.controlDate = value;
    }

    /**
     * Gets the value of the firstChangedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstChangedDate() {
        return firstChangedDate;
    }

    /**
     * Sets the value of the firstChangedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstChangedDate(XMLGregorianCalendar value) {
        this.firstChangedDate = value;
    }

    /**
     * Gets the value of the generationBatchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerationBatchType() {
        return generationBatchType;
    }

    /**
     * Sets the value of the generationBatchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerationBatchType(String value) {
        this.generationBatchType = value;
    }

    /**
     * Gets the value of the generationProcessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerationProcessType() {
        return generationProcessType;
    }

    /**
     * Sets the value of the generationProcessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerationProcessType(String value) {
        this.generationProcessType = value;
    }

    /**
     * Gets the value of the modifiedAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedAction() {
        return modifiedAction;
    }

    /**
     * Sets the value of the modifiedAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedAction(String value) {
        this.modifiedAction = value;
    }

    /**
     * Gets the value of the modifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * Sets the value of the modifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedBy(String value) {
        this.modifiedBy = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedDate(XMLGregorianCalendar value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the modifiedLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedLocation() {
        return modifiedLocation;
    }

    /**
     * Sets the value of the modifiedLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedLocation(String value) {
        this.modifiedLocation = value;
    }

    /**
     * Gets the value of the modifiedProcess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedProcess() {
        return modifiedProcess;
    }

    /**
     * Sets the value of the modifiedProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedProcess(String value) {
        this.modifiedProcess = value;
    }

    /**
     * Gets the value of the processingStationLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getProcessingStationLocationID() {
        return processingStationLocationID;
    }

    /**
     * Sets the value of the processingStationLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProcessingStationLocationID(Long value) {
        this.processingStationLocationID = value;
    }

    /**
     * Gets the value of the ratingAwardSummaryID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRatingAwardSummaryID() {
        return ratingAwardSummaryID;
    }

    /**
     * Sets the value of the ratingAwardSummaryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRatingAwardSummaryID(Long value) {
        this.ratingAwardSummaryID = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the stationOfJurisdictionLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStationOfJurisdictionLocationID() {
        return stationOfJurisdictionLocationID;
    }

    /**
     * Sets the value of the stationOfJurisdictionLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStationOfJurisdictionLocationID(Long value) {
        this.stationOfJurisdictionLocationID = value;
    }

    /**
     * Gets the value of the totalNetAmountDue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalNetAmountDue() {
        return totalNetAmountDue;
    }

    /**
     * Sets the value of the totalNetAmountDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalNetAmountDue(BigDecimal value) {
        this.totalNetAmountDue = value;
    }

    /**
     * Gets the value of the veteranID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVeteranID() {
        return veteranID;
    }

    /**
     * Sets the value of the veteranID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVeteranID(Long value) {
        this.veteranID = value;
    }

}
