//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 04:43:13 PM CDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.awards.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hClaimsVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hClaimsVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="claimList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="claimVO" type="{http://gov.va.vba.benefits.awards.ws/services}claimVO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hClaimsVO", propOrder = {
    "claimList"
})
public class HClaimsVO {

    protected HClaimsVO.ClaimList claimList;

    /**
     * Gets the value of the claimList property.
     * 
     * @return
     *     possible object is
     *     {@link HClaimsVO.ClaimList }
     *     
     */
    public HClaimsVO.ClaimList getClaimList() {
        return claimList;
    }

    /**
     * Sets the value of the claimList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HClaimsVO.ClaimList }
     *     
     */
    public void setClaimList(HClaimsVO.ClaimList value) {
        this.claimList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="claimVO" type="{http://gov.va.vba.benefits.awards.ws/services}claimVO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "claimVO"
    })
    public static class ClaimList {

        protected List<ClaimVO> claimVO;

        /**
         * Gets the value of the claimVO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the claimVO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClaimVO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClaimVO }
         * 
         * 
         */
        public List<ClaimVO> getClaimVO() {
            if (claimVO == null) {
                claimVO = new ArrayList<ClaimVO>();
            }
            return this.claimVO;
        }

    }

}
