//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 04:43:13 PM CDT 
//


package gov.va.vba.rbps.services.ws.client.mapping.awards.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.va.vba.rbps.services.ws.client.mapping.awards.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HAwardEvent_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "HAwardEvent");
    private final static QName _FindCurrentAndProposedAward_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "findCurrentAndProposedAward");
    private final static QName _AllotmentDecision_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AllotmentDecision");
    private final static QName _ValidateClaimJurisdictionResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "validateClaimJurisdictionResponse");
    private final static QName _AwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardResponse");
    private final static QName _BaseEligibilityDecision_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "BaseEligibilityDecision");
    private final static QName _Award_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "Award");
    private final static QName _ReadAwardLetterDataResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readAwardLetterDataResponse");
    private final static QName _HAwardLine_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "HAwardLine");
    private final static QName _ReadAwardChangedHistory_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readAwardChangedHistory");
    private final static QName _AwardClaimRelationshipDetailInputVO_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardClaimRelationshipDetailInputVO");
    private final static QName _GenerateAwardInput_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "GenerateAwardInput");
    private final static QName _DevelopmentActionGroup_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "DevelopmentActionGroup");
    private final static QName _ConcurProposedAwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "concurProposedAwardResponse");
    private final static QName _Data_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "Data");
    private final static QName _AwardClaimantResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardClaimantResponse");
    private final static QName _ReadApportionClaimantsResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readApportionClaimantsResponse");
    private final static QName _ReadSuspendResumeHistory_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readSuspendResumeHistory");
    private final static QName _ProgramTypeCode_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "ProgramTypeCode");
    private final static QName _ReadApportionClaimants_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readApportionClaimants");
    private final static QName _AuthorizeProposedAwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "authorizeProposedAwardResponse");
    private final static QName _StatusResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "StatusResponse");
    private final static QName _AwardHistoryResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardHistoryResponse");
    private final static QName _ReadParticipantAwards_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readParticipantAwards");
    private final static QName _FindGAOWorksheetResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "findGAOWorksheetResponse");
    private final static QName _ReadParticipantAwardsResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readParticipantAwardsResponse");
    private final static QName _ParticipantAwardsResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "ParticipantAwardsResponse");
    private final static QName _GenerateProposedAward_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "generateProposedAward");
    private final static QName _AwardClaimDetails_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardClaimDetails");
    private final static QName _AwardAddressDisplay_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardAddressDisplay");
    private final static QName _FindCurrentAndProposedAwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "findCurrentAndProposedAwardResponse");
    private final static QName _AuthorizeProposedAward_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "authorizeProposedAward");
    private final static QName _AwardLine_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardLine");
    private final static QName _ReadAwardChangedHistoryResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readAwardChangedHistoryResponse");
    private final static QName _ReadAwardValidHistoryResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readAwardValidHistoryResponse");
    private final static QName _CreateParticipantAward_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "createParticipantAward");
    private final static QName _AwardEventId_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardEventId");
    private final static QName _AwardClaimRelationshipDetail_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardClaimRelationshipDetail");
    private final static QName _ValidateClaimJurisdiction_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "validateClaimJurisdiction");
    private final static QName _ReturnProposedAward_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "returnProposedAward");
    private final static QName _ReadAwardLetterData_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readAwardLetterData");
    private final static QName _GenerateProposedAwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "generateProposedAwardResponse");
    private final static QName _ReadAwardValidHistory_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readAwardValidHistory");
    private final static QName _HClaims_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "HClaims");
    private final static QName _FindGAOWorksheet_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "findGAOWorksheet");
    private final static QName _ReadAwardHistoryResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readAwardHistoryResponse");
    private final static QName _CreateParticipantAwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "createParticipantAwardResponse");
    private final static QName _AwardKeyInput_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardKeyInput");
    private final static QName _RecipientEvent_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "RecipientEvent");
    private final static QName _AwardClaimRelationship_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardClaimRelationship");
    private final static QName _AwardHistory_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardHistory");
    private final static QName _AuthorizationProposedResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AuthorizationProposedResponse");
    private final static QName _AwardEventStatusResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardEventStatusResponse");
    private final static QName _AwardEventID_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardEventID");
    private final static QName _AwardReason_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardReason");
    private final static QName _AwardEventInput_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardEventInput");
    private final static QName _Claim_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "Claim");
    private final static QName _Message_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "Message");
    private final static QName _AwardEvent_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardEvent");
    private final static QName _ReadDisallowanceResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readDisallowanceResponse");
    private final static QName _Response_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "Response");
    private final static QName _ReadCurrentAndProposedAward_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readCurrentAndProposedAward");
    private final static QName _AuthorizationResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AuthorizationResponse");
    private final static QName _AwardClaimant_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardClaimant");
    private final static QName _DataValidationFaultBean_QNAME = new QName("http://gov.va.vba.benefits.arch.soap/webfault", "DataValidationFaultBean");
    private final static QName _ProposedAwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "ProposedAwardResponse");
    private final static QName _AuthorizationEvent_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AuthorizationEvent");
    private final static QName _BenefitsFaultBean_QNAME = new QName("http://gov.va.vba.benefits.arch.soap/webfault", "BenefitsFaultBean");
    private final static QName _AwardLetterDataResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardLetterDataResponse");
    private final static QName _BenefitsFault_QNAME = new QName("http://gov.va.vba.benefits.arch.soap/webfault", "BenefitsFault");
    private final static QName _CurrAndPropAwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "CurrAndPropAwardResponse");
    private final static QName _AwardClaimDetail_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "AwardClaimDetail");
    private final static QName _GAOWorksheet_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "GAOWorksheet");
    private final static QName _VeteranId_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "VeteranId");
    private final static QName _GAOWorksheetResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "GAOWorksheetResponse");
    private final static QName _ConcurProposedAward_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "concurProposedAward");
    private final static QName _AwardRecipient_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardRecipient");
    private final static QName _HAwardEventData_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "HAwardEventData");
    private final static QName _ReadAwardHistory_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readAwardHistory");
    private final static QName _ReturnProposedAwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "returnProposedAwardResponse");
    private final static QName _AwardLineRecipient_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardLineRecipient");
    private final static QName _MilitaryServicePeriod_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "MilitaryServicePeriod");
    private final static QName _DataValidationFault_QNAME = new QName("http://gov.va.vba.benefits.arch.soap/webfault", "DataValidationFault");
    private final static QName _ReadCurrentAndProposedAwardResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readCurrentAndProposedAwardResponse");
    private final static QName _ReadSuspendResumeHistoryResponse_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readSuspendResumeHistoryResponse");
    private final static QName _ReadDisallowance_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "readDisallowance");
    private final static QName _AwardProfile_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "AwardProfile");
    private final static QName _BeneficiaryId_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/data", "BeneficiaryId");
    private final static QName _AwardEventData_QNAME = new QName("http://gov.va.vba.benefits.awards.ws/services", "awardEventData");
    private final static QName _BenefitsFaultBeanDatabaseMessage_QNAME = new QName("", "databaseMessage");
    private final static QName _BenefitsFaultBeanModifiedLocation_QNAME = new QName("", "modifiedLocation");
    private final static QName _BenefitsFaultBeanSourceErrorID_QNAME = new QName("", "sourceErrorID");
    private final static QName _BenefitsFaultBeanModifiedProcess_QNAME = new QName("", "modifiedProcess");
    private final static QName _BenefitsFaultBeanModifiedBy_QNAME = new QName("", "modifiedBy");
    private final static QName _BenefitsFaultBeanObject_QNAME = new QName("", "object");
    private final static QName _BenefitsFaultBeanModifiedDate_QNAME = new QName("", "modifiedDate");
    private final static QName _BenefitsFaultBeanModifiedAction_QNAME = new QName("", "modifiedAction");
    private final static QName _BenefitsFaultBeanExceptionInfo_QNAME = new QName("", "exceptionInfo");
    private final static QName _BenefitsFaultBeanMessageID_QNAME = new QName("", "messageID");
    private final static QName _BenefitsFaultBeanSource_QNAME = new QName("", "source");
    private final static QName _BenefitsFaultBeanLogIt_QNAME = new QName("", "logIt");
    private final static QName _BenefitsFaultBeanFieldName_QNAME = new QName("", "fieldName");
    private final static QName _BenefitsFaultBeanRowIdentifier_QNAME = new QName("", "rowIdentifier");
    private final static QName _BenefitsFaultBeanSourceMessage_QNAME = new QName("", "sourceMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.va.vba.rbps.services.ws.client.mapping.awards.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReadAwardHistory }
     * 
     */
    public ReadAwardHistory createReadAwardHistory() {
        return new ReadAwardHistory();
    }

    /**
     * Create an instance of {@link GenerateAwardInput.Data }
     * 
     */
    public GenerateAwardInput.Data createGenerateAwardInputData() {
        return new GenerateAwardInput.Data();
    }

    /**
     * Create an instance of {@link AwardLetterDataResponseVO }
     * 
     */
    public AwardLetterDataResponseVO createAwardLetterDataResponseVO() {
        return new AwardLetterDataResponseVO();
    }

    /**
     * Create an instance of {@link ReadAwardChangedHistory }
     * 
     */
    public ReadAwardChangedHistory createReadAwardChangedHistory() {
        return new ReadAwardChangedHistory();
    }

    /**
     * Create an instance of {@link AwardHistoryResponse.RecipientEventRecords }
     * 
     */
    public AwardHistoryResponse.RecipientEventRecords createAwardHistoryResponseRecipientEventRecords() {
        return new AwardHistoryResponse.RecipientEventRecords();
    }

    /**
     * Create an instance of {@link AwardClaimRelationshipDetailInputVO }
     * 
     */
    public AwardClaimRelationshipDetailInputVO createAwardClaimRelationshipDetailInputVO() {
        return new AwardClaimRelationshipDetailInputVO();
    }

    /**
     * Create an instance of {@link ReadAwardLetterData }
     * 
     */
    public ReadAwardLetterData createReadAwardLetterData() {
        return new ReadAwardLetterData();
    }

    /**
     * Create an instance of {@link MilitaryServicePeriodVO }
     * 
     */
    public MilitaryServicePeriodVO createMilitaryServicePeriodVO() {
        return new MilitaryServicePeriodVO();
    }

    /**
     * Create an instance of {@link CurrAndPropAwardResponse.AwardRecipientList }
     * 
     */
    public CurrAndPropAwardResponse.AwardRecipientList createCurrAndPropAwardResponseAwardRecipientList() {
        return new CurrAndPropAwardResponse.AwardRecipientList();
    }

    /**
     * Create an instance of {@link ReadDisallowanceResponse }
     * 
     */
    public ReadDisallowanceResponse createReadDisallowanceResponse() {
        return new ReadDisallowanceResponse();
    }

    /**
     * Create an instance of {@link ReadDisallowance }
     * 
     */
    public ReadDisallowance createReadDisallowance() {
        return new ReadDisallowance();
    }

    /**
     * Create an instance of {@link DataValidationFault }
     * 
     */
    public DataValidationFault createDataValidationFault() {
        return new DataValidationFault();
    }

    /**
     * Create an instance of {@link CreateParticipantAward }
     * 
     */
    public CreateParticipantAward createCreateParticipantAward() {
        return new CreateParticipantAward();
    }

    /**
     * Create an instance of {@link GaoWorksheetVO }
     * 
     */
    public GaoWorksheetVO createGaoWorksheetVO() {
        return new GaoWorksheetVO();
    }

    /**
     * Create an instance of {@link GenerateAwardInput.AwardClaims }
     * 
     */
    public GenerateAwardInput.AwardClaims createGenerateAwardInputAwardClaims() {
        return new GenerateAwardInput.AwardClaims();
    }

    /**
     * Create an instance of {@link CurrAndPropAwardResponse.AwardEventList }
     * 
     */
    public CurrAndPropAwardResponse.AwardEventList createCurrAndPropAwardResponseAwardEventList() {
        return new CurrAndPropAwardResponse.AwardEventList();
    }

    /**
     * Create an instance of {@link ReadAwardHistoryResponse }
     * 
     */
    public ReadAwardHistoryResponse createReadAwardHistoryResponse() {
        return new ReadAwardHistoryResponse();
    }

    /**
     * Create an instance of {@link ReadCurrentAndProposedAward }
     * 
     */
    public ReadCurrentAndProposedAward createReadCurrentAndProposedAward() {
        return new ReadCurrentAndProposedAward();
    }

    /**
     * Create an instance of {@link ValidateClaimJurisdictionResponse }
     * 
     */
    public ValidateClaimJurisdictionResponse createValidateClaimJurisdictionResponse() {
        return new ValidateClaimJurisdictionResponse();
    }

    /**
     * Create an instance of {@link AwardHistoryResponse.AuthorizationEventRecords }
     * 
     */
    public AwardHistoryResponse.AuthorizationEventRecords createAwardHistoryResponseAuthorizationEventRecords() {
        return new AwardHistoryResponse.AuthorizationEventRecords();
    }

    /**
     * Create an instance of {@link GenerateProposedAwardResponse }
     * 
     */
    public GenerateProposedAwardResponse createGenerateProposedAwardResponse() {
        return new GenerateProposedAwardResponse();
    }

    /**
     * Create an instance of {@link ParticipantAwardsResponse }
     * 
     */
    public ParticipantAwardsResponse createParticipantAwardsResponse() {
        return new ParticipantAwardsResponse();
    }

    /**
     * Create an instance of {@link ReadCurrentAndProposedAwardResponse }
     * 
     */
    public ReadCurrentAndProposedAwardResponse createReadCurrentAndProposedAwardResponse() {
        return new ReadCurrentAndProposedAwardResponse();
    }

    /**
     * Create an instance of {@link ReadParticipantAwardsResponse }
     * 
     */
    public ReadParticipantAwardsResponse createReadParticipantAwardsResponse() {
        return new ReadParticipantAwardsResponse();
    }

    /**
     * Create an instance of {@link CurrAndPropAwardResponse }
     * 
     */
    public CurrAndPropAwardResponse createCurrAndPropAwardResponse() {
        return new CurrAndPropAwardResponse();
    }

    /**
     * Create an instance of {@link GAOWorksheetResponse }
     * 
     */
    public GAOWorksheetResponse createGAOWorksheetResponse() {
        return new GAOWorksheetResponse();
    }

    /**
     * Create an instance of {@link ReadAwardValidHistory }
     * 
     */
    public ReadAwardValidHistory createReadAwardValidHistory() {
        return new ReadAwardValidHistory();
    }

    /**
     * Create an instance of {@link AwardResponse }
     * 
     */
    public AwardResponse createAwardResponse() {
        return new AwardResponse();
    }

    /**
     * Create an instance of {@link AwardReasonVO }
     * 
     */
    public AwardReasonVO createAwardReasonVO() {
        return new AwardReasonVO();
    }

    /**
     * Create an instance of {@link ProposedAwardResponse.AwardClaims }
     * 
     */
    public ProposedAwardResponse.AwardClaims createProposedAwardResponseAwardClaims() {
        return new ProposedAwardResponse.AwardClaims();
    }

    /**
     * Create an instance of {@link AwardHistoryResponse.DevelopmentActionGroupVORecords }
     * 
     */
    public AwardHistoryResponse.DevelopmentActionGroupVORecords createAwardHistoryResponseDevelopmentActionGroupVORecords() {
        return new AwardHistoryResponse.DevelopmentActionGroupVORecords();
    }

    /**
     * Create an instance of {@link ValidateClaimJurisdiction }
     * 
     */
    public ValidateClaimJurisdiction createValidateClaimJurisdiction() {
        return new ValidateClaimJurisdiction();
    }

    /**
     * Create an instance of {@link DevelopmentActionGroupVO }
     * 
     */
    public DevelopmentActionGroupVO createDevelopmentActionGroupVO() {
        return new DevelopmentActionGroupVO();
    }

    /**
     * Create an instance of {@link HAwardEventDataVO }
     * 
     */
    public HAwardEventDataVO createHAwardEventDataVO() {
        return new HAwardEventDataVO();
    }

    /**
     * Create an instance of {@link gov.va.vba.rbps.services.ws.client.mapping.awards.service.VoReturnBase.MessageList }
     * 
     */
    public gov.va.vba.rbps.services.ws.client.mapping.awards.service.VoReturnBase.MessageList createVoReturnBaseMessageList() {
        return new gov.va.vba.rbps.services.ws.client.mapping.awards.service.VoReturnBase.MessageList();
    }

    /**
     * Create an instance of {@link AuthorizationResponseVO.DevelopmentActionGroups }
     * 
     */
    public AuthorizationResponseVO.DevelopmentActionGroups createAuthorizationResponseVODevelopmentActionGroups() {
        return new AuthorizationResponseVO.DevelopmentActionGroups();
    }

    /**
     * Create an instance of {@link DataVO }
     * 
     */
    public DataVO createDataVO() {
        return new DataVO();
    }

    /**
     * Create an instance of {@link ParticipantAwardsResponse.Awards }
     * 
     */
    public ParticipantAwardsResponse.Awards createParticipantAwardsResponseAwards() {
        return new ParticipantAwardsResponse.Awards();
    }

    /**
     * Create an instance of {@link AwardProfileVO }
     * 
     */
    public AwardProfileVO createAwardProfileVO() {
        return new AwardProfileVO();
    }

    /**
     * Create an instance of {@link AwardLineRecipientVO }
     * 
     */
    public AwardLineRecipientVO createAwardLineRecipientVO() {
        return new AwardLineRecipientVO();
    }

    /**
     * Create an instance of {@link ProposedAwardResponse.AwardAddressDisplays }
     * 
     */
    public ProposedAwardResponse.AwardAddressDisplays createProposedAwardResponseAwardAddressDisplays() {
        return new ProposedAwardResponse.AwardAddressDisplays();
    }

    /**
     * Create an instance of {@link HAwardLineVO }
     * 
     */
    public HAwardLineVO createHAwardLineVO() {
        return new HAwardLineVO();
    }

    /**
     * Create an instance of {@link ReadSuspendResumeHistory }
     * 
     */
    public ReadSuspendResumeHistory createReadSuspendResumeHistory() {
        return new ReadSuspendResumeHistory();
    }

    /**
     * Create an instance of {@link GenerateAwardInput.RecipientEvent }
     * 
     */
    public GenerateAwardInput.RecipientEvent createGenerateAwardInputRecipientEvent() {
        return new GenerateAwardInput.RecipientEvent();
    }

    /**
     * Create an instance of {@link AwardLineVO }
     * 
     */
    public AwardLineVO createAwardLineVO() {
        return new AwardLineVO();
    }

    /**
     * Create an instance of {@link AwardHistoryResponse.AwardHistoryRecords }
     * 
     */
    public AwardHistoryResponse.AwardHistoryRecords createAwardHistoryResponseAwardHistoryRecords() {
        return new AwardHistoryResponse.AwardHistoryRecords();
    }

    /**
     * Create an instance of {@link AwardKeyInputVO }
     * 
     */
    public AwardKeyInputVO createAwardKeyInputVO() {
        return new AwardKeyInputVO();
    }

    /**
     * Create an instance of {@link ParticipantAwardsResponse.AwardProfiles }
     * 
     */
    public ParticipantAwardsResponse.AwardProfiles createParticipantAwardsResponseAwardProfiles() {
        return new ParticipantAwardsResponse.AwardProfiles();
    }

    /**
     * Create an instance of {@link AwardClaimRelationshipVO }
     * 
     */
    public AwardClaimRelationshipVO createAwardClaimRelationshipVO() {
        return new AwardClaimRelationshipVO();
    }

    /**
     * Create an instance of {@link ClaimVO }
     * 
     */
    public ClaimVO createClaimVO() {
        return new ClaimVO();
    }

    /**
     * Create an instance of {@link ProposedAwardResponse }
     * 
     */
    public ProposedAwardResponse createProposedAwardResponse() {
        return new ProposedAwardResponse();
    }

    /**
     * Create an instance of {@link BenefitsFaultBean }
     * 
     */
    public BenefitsFaultBean createBenefitsFaultBean() {
        return new BenefitsFaultBean();
    }

    /**
     * Create an instance of {@link AwardClaimantResponse.AwardClaimants }
     * 
     */
    public AwardClaimantResponse.AwardClaimants createAwardClaimantResponseAwardClaimants() {
        return new AwardClaimantResponse.AwardClaimants();
    }

    /**
     * Create an instance of {@link ReadApportionClaimantsResponse }
     * 
     */
    public ReadApportionClaimantsResponse createReadApportionClaimantsResponse() {
        return new ReadApportionClaimantsResponse();
    }

    /**
     * Create an instance of {@link ResponseVO }
     * 
     */
    public ResponseVO createResponseVO() {
        return new ResponseVO();
    }

    /**
     * Create an instance of {@link ProposedAwardResponse.MilitaryServicePeriods }
     * 
     */
    public ProposedAwardResponse.MilitaryServicePeriods createProposedAwardResponseMilitaryServicePeriods() {
        return new ProposedAwardResponse.MilitaryServicePeriods();
    }

    /**
     * Create an instance of {@link ProposedAwardResponse.AwardEventList }
     * 
     */
    public ProposedAwardResponse.AwardEventList createProposedAwardResponseAwardEventList() {
        return new ProposedAwardResponse.AwardEventList();
    }

    /**
     * Create an instance of {@link StatusResponse }
     * 
     */
    public StatusResponse createStatusResponse() {
        return new StatusResponse();
    }

    /**
     * Create an instance of {@link AwardHistoryResponse }
     * 
     */
    public AwardHistoryResponse createAwardHistoryResponse() {
        return new AwardHistoryResponse();
    }

    /**
     * Create an instance of {@link AuthorizeProposedAward }
     * 
     */
    public AuthorizeProposedAward createAuthorizeProposedAward() {
        return new AuthorizeProposedAward();
    }

    /**
     * Create an instance of {@link CurrAndPropAwardResponse.AwardList }
     * 
     */
    public CurrAndPropAwardResponse.AwardList createCurrAndPropAwardResponseAwardList() {
        return new CurrAndPropAwardResponse.AwardList();
    }

    /**
     * Create an instance of {@link ReturnProposedAward }
     * 
     */
    public ReturnProposedAward createReturnProposedAward() {
        return new ReturnProposedAward();
    }

    /**
     * Create an instance of {@link MessageVO }
     * 
     */
    public MessageVO createMessageVO() {
        return new MessageVO();
    }

    /**
     * Create an instance of {@link AwardEventDataVO }
     * 
     */
    public AwardEventDataVO createAwardEventDataVO() {
        return new AwardEventDataVO();
    }

    /**
     * Create an instance of {@link AwardClaimantVO }
     * 
     */
    public AwardClaimantVO createAwardClaimantVO() {
        return new AwardClaimantVO();
    }

    /**
     * Create an instance of {@link AuthorizeProposedAwardResponse }
     * 
     */
    public AuthorizeProposedAwardResponse createAuthorizeProposedAwardResponse() {
        return new AuthorizeProposedAwardResponse();
    }

    /**
     * Create an instance of {@link AwardClaimRelationshipDetailInputVO.AwardClaimRelationshipDetails }
     * 
     */
    public AwardClaimRelationshipDetailInputVO.AwardClaimRelationshipDetails createAwardClaimRelationshipDetailInputVOAwardClaimRelationshipDetails() {
        return new AwardClaimRelationshipDetailInputVO.AwardClaimRelationshipDetails();
    }

    /**
     * Create an instance of {@link HClaimsVO.ClaimList }
     * 
     */
    public HClaimsVO.ClaimList createHClaimsVOClaimList() {
        return new HClaimsVO.ClaimList();
    }

    /**
     * Create an instance of {@link HAwardEventVO.HAwardLineList }
     * 
     */
    public HAwardEventVO.HAwardLineList createHAwardEventVOHAwardLineList() {
        return new HAwardEventVO.HAwardLineList();
    }

    /**
     * Create an instance of {@link AwardHistoryResponse.AllotmentDecisionRecords }
     * 
     */
    public AwardHistoryResponse.AllotmentDecisionRecords createAwardHistoryResponseAllotmentDecisionRecords() {
        return new AwardHistoryResponse.AllotmentDecisionRecords();
    }

    /**
     * Create an instance of {@link ProposedAwardResponse.Awards }
     * 
     */
    public ProposedAwardResponse.Awards createProposedAwardResponseAwards() {
        return new ProposedAwardResponse.Awards();
    }

    /**
     * Create an instance of {@link FindCurrentAndProposedAwardResponse }
     * 
     */
    public FindCurrentAndProposedAwardResponse createFindCurrentAndProposedAwardResponse() {
        return new FindCurrentAndProposedAwardResponse();
    }

    /**
     * Create an instance of {@link ReadParticipantAwards }
     * 
     */
    public ReadParticipantAwards createReadParticipantAwards() {
        return new ReadParticipantAwards();
    }

    /**
     * Create an instance of {@link AuthorizationResponseVO.AwardRecipients }
     * 
     */
    public AuthorizationResponseVO.AwardRecipients createAuthorizationResponseVOAwardRecipients() {
        return new AuthorizationResponseVO.AwardRecipients();
    }

    /**
     * Create an instance of {@link DataValidationFaultBean }
     * 
     */
    public DataValidationFaultBean createDataValidationFaultBean() {
        return new DataValidationFaultBean();
    }

    /**
     * Create an instance of {@link AwardHistoryResponse.AwardEventRecords }
     * 
     */
    public AwardHistoryResponse.AwardEventRecords createAwardHistoryResponseAwardEventRecords() {
        return new AwardHistoryResponse.AwardEventRecords();
    }

    /**
     * Create an instance of {@link BaseEligibilityDecisionVO }
     * 
     */
    public BaseEligibilityDecisionVO createBaseEligibilityDecisionVO() {
        return new BaseEligibilityDecisionVO();
    }

    /**
     * Create an instance of {@link ProposedAwardResponse.AuthorizationEvents }
     * 
     */
    public ProposedAwardResponse.AuthorizationEvents createProposedAwardResponseAuthorizationEvents() {
        return new ProposedAwardResponse.AuthorizationEvents();
    }

    /**
     * Create an instance of {@link GAOWorksheetResponse.GAOWorksheets }
     * 
     */
    public GAOWorksheetResponse.GAOWorksheets createGAOWorksheetResponseGAOWorksheets() {
        return new GAOWorksheetResponse.GAOWorksheets();
    }

    /**
     * Create an instance of {@link AwardClaimRelationshipDetailVO }
     * 
     */
    public AwardClaimRelationshipDetailVO createAwardClaimRelationshipDetailVO() {
        return new AwardClaimRelationshipDetailVO();
    }

    /**
     * Create an instance of {@link ProposedAwardResponse.BasicEligibilities }
     * 
     */
    public ProposedAwardResponse.BasicEligibilities createProposedAwardResponseBasicEligibilities() {
        return new ProposedAwardResponse.BasicEligibilities();
    }

    /**
     * Create an instance of {@link ReadAwardChangedHistoryResponse }
     * 
     */
    public ReadAwardChangedHistoryResponse createReadAwardChangedHistoryResponse() {
        return new ReadAwardChangedHistoryResponse();
    }

    /**
     * Create an instance of {@link FindGAOWorksheet }
     * 
     */
    public FindGAOWorksheet createFindGAOWorksheet() {
        return new FindGAOWorksheet();
    }

    /**
     * Create an instance of {@link AuthorizationResponseVO }
     * 
     */
    public AuthorizationResponseVO createAuthorizationResponseVO() {
        return new AuthorizationResponseVO();
    }

    /**
     * Create an instance of {@link CurrAndPropAwardResponse.AuthorizationEventList }
     * 
     */
    public CurrAndPropAwardResponse.AuthorizationEventList createCurrAndPropAwardResponseAuthorizationEventList() {
        return new CurrAndPropAwardResponse.AuthorizationEventList();
    }

    /**
     * Create an instance of {@link AwardRecipientVO }
     * 
     */
    public AwardRecipientVO createAwardRecipientVO() {
        return new AwardRecipientVO();
    }

    /**
     * Create an instance of {@link AwardResponse.Awards }
     * 
     */
    public AwardResponse.Awards createAwardResponseAwards() {
        return new AwardResponse.Awards();
    }

    /**
     * Create an instance of {@link FaultInfoBean }
     * 
     */
    public FaultInfoBean createFaultInfoBean() {
        return new FaultInfoBean();
    }

    /**
     * Create an instance of {@link FindGAOWorksheetResponse }
     * 
     */
    public FindGAOWorksheetResponse createFindGAOWorksheetResponse() {
        return new FindGAOWorksheetResponse();
    }

    /**
     * Create an instance of {@link AwardHistoryVO }
     * 
     */
    public AwardHistoryVO createAwardHistoryVO() {
        return new AwardHistoryVO();
    }

    /**
     * Create an instance of {@link CreateParticipantAwardResponse }
     * 
     */
    public CreateParticipantAwardResponse createCreateParticipantAwardResponse() {
        return new CreateParticipantAwardResponse();
    }

    /**
     * Create an instance of {@link ProposedAwardResponse.AwardRecipients }
     * 
     */
    public ProposedAwardResponse.AwardRecipients createProposedAwardResponseAwardRecipients() {
        return new ProposedAwardResponse.AwardRecipients();
    }

    /**
     * Create an instance of {@link AwardEventStatusResponse.AwardEvents }
     * 
     */
    public AwardEventStatusResponse.AwardEvents createAwardEventStatusResponseAwardEvents() {
        return new AwardEventStatusResponse.AwardEvents();
    }

    /**
     * Create an instance of {@link GenerateProposedAward }
     * 
     */
    public GenerateProposedAward createGenerateProposedAward() {
        return new GenerateProposedAward();
    }

    /**
     * Create an instance of {@link RecipientEventVO }
     * 
     */
    public RecipientEventVO createRecipientEventVO() {
        return new RecipientEventVO();
    }

    /**
     * Create an instance of {@link GenerateAwardInput }
     * 
     */
    public GenerateAwardInput createGenerateAwardInput() {
        return new GenerateAwardInput();
    }

    /**
     * Create an instance of {@link ReadSuspendResumeHistoryResponse }
     * 
     */
    public ReadSuspendResumeHistoryResponse createReadSuspendResumeHistoryResponse() {
        return new ReadSuspendResumeHistoryResponse();
    }

    /**
     * Create an instance of {@link HAwardLineVO.AwardLineRecipientList }
     * 
     */
    public HAwardLineVO.AwardLineRecipientList createHAwardLineVOAwardLineRecipientList() {
        return new HAwardLineVO.AwardLineRecipientList();
    }

    /**
     * Create an instance of {@link AwardEventStatusResponse.Awards }
     * 
     */
    public AwardEventStatusResponse.Awards createAwardEventStatusResponseAwards() {
        return new AwardEventStatusResponse.Awards();
    }

    /**
     * Create an instance of {@link AwardAddressDisplayVO }
     * 
     */
    public AwardAddressDisplayVO createAwardAddressDisplayVO() {
        return new AwardAddressDisplayVO();
    }

    /**
     * Create an instance of {@link ConcurProposedAwardResponse }
     * 
     */
    public ConcurProposedAwardResponse createConcurProposedAwardResponse() {
        return new ConcurProposedAwardResponse();
    }

    /**
     * Create an instance of {@link AllotmentDecisionVO }
     * 
     */
    public AllotmentDecisionVO createAllotmentDecisionVO() {
        return new AllotmentDecisionVO();
    }

    /**
     * Create an instance of {@link HAwardLineVO.AwardReasonList }
     * 
     */
    public HAwardLineVO.AwardReasonList createHAwardLineVOAwardReasonList() {
        return new HAwardLineVO.AwardReasonList();
    }

    /**
     * Create an instance of {@link HAwardEventVO }
     * 
     */
    public HAwardEventVO createHAwardEventVO() {
        return new HAwardEventVO();
    }

    /**
     * Create an instance of {@link ConcurProposedAward }
     * 
     */
    public ConcurProposedAward createConcurProposedAward() {
        return new ConcurProposedAward();
    }

    /**
     * Create an instance of {@link AwardEventStatusResponse.AuthorizationEvents }
     * 
     */
    public AwardEventStatusResponse.AuthorizationEvents createAwardEventStatusResponseAuthorizationEvents() {
        return new AwardEventStatusResponse.AuthorizationEvents();
    }

    /**
     * Create an instance of {@link HClaimsVO }
     * 
     */
    public HClaimsVO createHClaimsVO() {
        return new HClaimsVO();
    }

    /**
     * Create an instance of {@link AwardVO }
     * 
     */
    public AwardVO createAwardVO() {
        return new AwardVO();
    }

    /**
     * Create an instance of {@link ReadApportionClaimants }
     * 
     */
    public ReadApportionClaimants createReadApportionClaimants() {
        return new ReadApportionClaimants();
    }

    /**
     * Create an instance of {@link AuthorizationEventVO }
     * 
     */
    public AuthorizationEventVO createAuthorizationEventVO() {
        return new AuthorizationEventVO();
    }

    /**
     * Create an instance of {@link AuthorizationResponseVO.AwardEvents }
     * 
     */
    public AuthorizationResponseVO.AwardEvents createAuthorizationResponseVOAwardEvents() {
        return new AuthorizationResponseVO.AwardEvents();
    }

    /**
     * Create an instance of {@link AwardClaimantResponse }
     * 
     */
    public AwardClaimantResponse createAwardClaimantResponse() {
        return new AwardClaimantResponse();
    }

    /**
     * Create an instance of {@link AwardEventStatusResponse }
     * 
     */
    public AwardEventStatusResponse createAwardEventStatusResponse() {
        return new AwardEventStatusResponse();
    }

    /**
     * Create an instance of {@link FindCurrentAndProposedAward }
     * 
     */
    public FindCurrentAndProposedAward createFindCurrentAndProposedAward() {
        return new FindCurrentAndProposedAward();
    }

    /**
     * Create an instance of {@link AwardEventVO }
     * 
     */
    public AwardEventVO createAwardEventVO() {
        return new AwardEventVO();
    }

    /**
     * Create an instance of {@link ReturnProposedAwardResponse }
     * 
     */
    public ReturnProposedAwardResponse createReturnProposedAwardResponse() {
        return new ReturnProposedAwardResponse();
    }

    /**
     * Create an instance of {@link ReadAwardLetterDataResponse }
     * 
     */
    public ReadAwardLetterDataResponse createReadAwardLetterDataResponse() {
        return new ReadAwardLetterDataResponse();
    }

    /**
     * Create an instance of {@link ReadAwardValidHistoryResponse }
     * 
     */
    public ReadAwardValidHistoryResponse createReadAwardValidHistoryResponse() {
        return new ReadAwardValidHistoryResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HAwardEventVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "HAwardEvent")
    public JAXBElement<HAwardEventVO> createHAwardEvent(HAwardEventVO value) {
        return new JAXBElement<HAwardEventVO>(_HAwardEvent_QNAME, HAwardEventVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindCurrentAndProposedAward }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "findCurrentAndProposedAward")
    public JAXBElement<FindCurrentAndProposedAward> createFindCurrentAndProposedAward(FindCurrentAndProposedAward value) {
        return new JAXBElement<FindCurrentAndProposedAward>(_FindCurrentAndProposedAward_QNAME, FindCurrentAndProposedAward.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllotmentDecisionVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AllotmentDecision")
    public JAXBElement<AllotmentDecisionVO> createAllotmentDecision(AllotmentDecisionVO value) {
        return new JAXBElement<AllotmentDecisionVO>(_AllotmentDecision_QNAME, AllotmentDecisionVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateClaimJurisdictionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "validateClaimJurisdictionResponse")
    public JAXBElement<ValidateClaimJurisdictionResponse> createValidateClaimJurisdictionResponse(ValidateClaimJurisdictionResponse value) {
        return new JAXBElement<ValidateClaimJurisdictionResponse>(_ValidateClaimJurisdictionResponse_QNAME, ValidateClaimJurisdictionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardResponse")
    public JAXBElement<AwardResponse> createAwardResponse(AwardResponse value) {
        return new JAXBElement<AwardResponse>(_AwardResponse_QNAME, AwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseEligibilityDecisionVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "BaseEligibilityDecision")
    public JAXBElement<BaseEligibilityDecisionVO> createBaseEligibilityDecision(BaseEligibilityDecisionVO value) {
        return new JAXBElement<BaseEligibilityDecisionVO>(_BaseEligibilityDecision_QNAME, BaseEligibilityDecisionVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "Award")
    public JAXBElement<AwardVO> createAward(AwardVO value) {
        return new JAXBElement<AwardVO>(_Award_QNAME, AwardVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAwardLetterDataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readAwardLetterDataResponse")
    public JAXBElement<ReadAwardLetterDataResponse> createReadAwardLetterDataResponse(ReadAwardLetterDataResponse value) {
        return new JAXBElement<ReadAwardLetterDataResponse>(_ReadAwardLetterDataResponse_QNAME, ReadAwardLetterDataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HAwardLineVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "HAwardLine")
    public JAXBElement<HAwardLineVO> createHAwardLine(HAwardLineVO value) {
        return new JAXBElement<HAwardLineVO>(_HAwardLine_QNAME, HAwardLineVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAwardChangedHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readAwardChangedHistory")
    public JAXBElement<ReadAwardChangedHistory> createReadAwardChangedHistory(ReadAwardChangedHistory value) {
        return new JAXBElement<ReadAwardChangedHistory>(_ReadAwardChangedHistory_QNAME, ReadAwardChangedHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardClaimRelationshipDetailInputVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardClaimRelationshipDetailInputVO")
    public JAXBElement<AwardClaimRelationshipDetailInputVO> createAwardClaimRelationshipDetailInputVO(AwardClaimRelationshipDetailInputVO value) {
        return new JAXBElement<AwardClaimRelationshipDetailInputVO>(_AwardClaimRelationshipDetailInputVO_QNAME, AwardClaimRelationshipDetailInputVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerateAwardInput }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "GenerateAwardInput")
    public JAXBElement<GenerateAwardInput> createGenerateAwardInput(GenerateAwardInput value) {
        return new JAXBElement<GenerateAwardInput>(_GenerateAwardInput_QNAME, GenerateAwardInput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DevelopmentActionGroupVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "DevelopmentActionGroup")
    public JAXBElement<DevelopmentActionGroupVO> createDevelopmentActionGroup(DevelopmentActionGroupVO value) {
        return new JAXBElement<DevelopmentActionGroupVO>(_DevelopmentActionGroup_QNAME, DevelopmentActionGroupVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConcurProposedAwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "concurProposedAwardResponse")
    public JAXBElement<ConcurProposedAwardResponse> createConcurProposedAwardResponse(ConcurProposedAwardResponse value) {
        return new JAXBElement<ConcurProposedAwardResponse>(_ConcurProposedAwardResponse_QNAME, ConcurProposedAwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "Data")
    public JAXBElement<DataVO> createData(DataVO value) {
        return new JAXBElement<DataVO>(_Data_QNAME, DataVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardClaimantResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardClaimantResponse")
    public JAXBElement<AwardClaimantResponse> createAwardClaimantResponse(AwardClaimantResponse value) {
        return new JAXBElement<AwardClaimantResponse>(_AwardClaimantResponse_QNAME, AwardClaimantResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadApportionClaimantsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readApportionClaimantsResponse")
    public JAXBElement<ReadApportionClaimantsResponse> createReadApportionClaimantsResponse(ReadApportionClaimantsResponse value) {
        return new JAXBElement<ReadApportionClaimantsResponse>(_ReadApportionClaimantsResponse_QNAME, ReadApportionClaimantsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadSuspendResumeHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readSuspendResumeHistory")
    public JAXBElement<ReadSuspendResumeHistory> createReadSuspendResumeHistory(ReadSuspendResumeHistory value) {
        return new JAXBElement<ReadSuspendResumeHistory>(_ReadSuspendResumeHistory_QNAME, ReadSuspendResumeHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "ProgramTypeCode")
    public JAXBElement<String> createProgramTypeCode(String value) {
        return new JAXBElement<String>(_ProgramTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadApportionClaimants }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readApportionClaimants")
    public JAXBElement<ReadApportionClaimants> createReadApportionClaimants(ReadApportionClaimants value) {
        return new JAXBElement<ReadApportionClaimants>(_ReadApportionClaimants_QNAME, ReadApportionClaimants.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizeProposedAwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "authorizeProposedAwardResponse")
    public JAXBElement<AuthorizeProposedAwardResponse> createAuthorizeProposedAwardResponse(AuthorizeProposedAwardResponse value) {
        return new JAXBElement<AuthorizeProposedAwardResponse>(_AuthorizeProposedAwardResponse_QNAME, AuthorizeProposedAwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "StatusResponse")
    public JAXBElement<StatusResponse> createStatusResponse(StatusResponse value) {
        return new JAXBElement<StatusResponse>(_StatusResponse_QNAME, StatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardHistoryResponse")
    public JAXBElement<AwardHistoryResponse> createAwardHistoryResponse(AwardHistoryResponse value) {
        return new JAXBElement<AwardHistoryResponse>(_AwardHistoryResponse_QNAME, AwardHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadParticipantAwards }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readParticipantAwards")
    public JAXBElement<ReadParticipantAwards> createReadParticipantAwards(ReadParticipantAwards value) {
        return new JAXBElement<ReadParticipantAwards>(_ReadParticipantAwards_QNAME, ReadParticipantAwards.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindGAOWorksheetResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "findGAOWorksheetResponse")
    public JAXBElement<FindGAOWorksheetResponse> createFindGAOWorksheetResponse(FindGAOWorksheetResponse value) {
        return new JAXBElement<FindGAOWorksheetResponse>(_FindGAOWorksheetResponse_QNAME, FindGAOWorksheetResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadParticipantAwardsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readParticipantAwardsResponse")
    public JAXBElement<ReadParticipantAwardsResponse> createReadParticipantAwardsResponse(ReadParticipantAwardsResponse value) {
        return new JAXBElement<ReadParticipantAwardsResponse>(_ReadParticipantAwardsResponse_QNAME, ReadParticipantAwardsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParticipantAwardsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "ParticipantAwardsResponse")
    public JAXBElement<ParticipantAwardsResponse> createParticipantAwardsResponse(ParticipantAwardsResponse value) {
        return new JAXBElement<ParticipantAwardsResponse>(_ParticipantAwardsResponse_QNAME, ParticipantAwardsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerateProposedAward }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "generateProposedAward")
    public JAXBElement<GenerateProposedAward> createGenerateProposedAward(GenerateProposedAward value) {
        return new JAXBElement<GenerateProposedAward>(_GenerateProposedAward_QNAME, GenerateProposedAward.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardClaimRelationshipDetailInputVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardClaimDetails")
    public JAXBElement<AwardClaimRelationshipDetailInputVO> createAwardClaimDetails(AwardClaimRelationshipDetailInputVO value) {
        return new JAXBElement<AwardClaimRelationshipDetailInputVO>(_AwardClaimDetails_QNAME, AwardClaimRelationshipDetailInputVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardAddressDisplayVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardAddressDisplay")
    public JAXBElement<AwardAddressDisplayVO> createAwardAddressDisplay(AwardAddressDisplayVO value) {
        return new JAXBElement<AwardAddressDisplayVO>(_AwardAddressDisplay_QNAME, AwardAddressDisplayVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindCurrentAndProposedAwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "findCurrentAndProposedAwardResponse")
    public JAXBElement<FindCurrentAndProposedAwardResponse> createFindCurrentAndProposedAwardResponse(FindCurrentAndProposedAwardResponse value) {
        return new JAXBElement<FindCurrentAndProposedAwardResponse>(_FindCurrentAndProposedAwardResponse_QNAME, FindCurrentAndProposedAwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizeProposedAward }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "authorizeProposedAward")
    public JAXBElement<AuthorizeProposedAward> createAuthorizeProposedAward(AuthorizeProposedAward value) {
        return new JAXBElement<AuthorizeProposedAward>(_AuthorizeProposedAward_QNAME, AuthorizeProposedAward.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardLineVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardLine")
    public JAXBElement<AwardLineVO> createAwardLine(AwardLineVO value) {
        return new JAXBElement<AwardLineVO>(_AwardLine_QNAME, AwardLineVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAwardChangedHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readAwardChangedHistoryResponse")
    public JAXBElement<ReadAwardChangedHistoryResponse> createReadAwardChangedHistoryResponse(ReadAwardChangedHistoryResponse value) {
        return new JAXBElement<ReadAwardChangedHistoryResponse>(_ReadAwardChangedHistoryResponse_QNAME, ReadAwardChangedHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAwardValidHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readAwardValidHistoryResponse")
    public JAXBElement<ReadAwardValidHistoryResponse> createReadAwardValidHistoryResponse(ReadAwardValidHistoryResponse value) {
        return new JAXBElement<ReadAwardValidHistoryResponse>(_ReadAwardValidHistoryResponse_QNAME, ReadAwardValidHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateParticipantAward }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "createParticipantAward")
    public JAXBElement<CreateParticipantAward> createCreateParticipantAward(CreateParticipantAward value) {
        return new JAXBElement<CreateParticipantAward>(_CreateParticipantAward_QNAME, CreateParticipantAward.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardEventId")
    public JAXBElement<Long> createAwardEventId(Long value) {
        return new JAXBElement<Long>(_AwardEventId_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardClaimRelationshipDetailVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardClaimRelationshipDetail")
    public JAXBElement<AwardClaimRelationshipDetailVO> createAwardClaimRelationshipDetail(AwardClaimRelationshipDetailVO value) {
        return new JAXBElement<AwardClaimRelationshipDetailVO>(_AwardClaimRelationshipDetail_QNAME, AwardClaimRelationshipDetailVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateClaimJurisdiction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "validateClaimJurisdiction")
    public JAXBElement<ValidateClaimJurisdiction> createValidateClaimJurisdiction(ValidateClaimJurisdiction value) {
        return new JAXBElement<ValidateClaimJurisdiction>(_ValidateClaimJurisdiction_QNAME, ValidateClaimJurisdiction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnProposedAward }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "returnProposedAward")
    public JAXBElement<ReturnProposedAward> createReturnProposedAward(ReturnProposedAward value) {
        return new JAXBElement<ReturnProposedAward>(_ReturnProposedAward_QNAME, ReturnProposedAward.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAwardLetterData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readAwardLetterData")
    public JAXBElement<ReadAwardLetterData> createReadAwardLetterData(ReadAwardLetterData value) {
        return new JAXBElement<ReadAwardLetterData>(_ReadAwardLetterData_QNAME, ReadAwardLetterData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerateProposedAwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "generateProposedAwardResponse")
    public JAXBElement<GenerateProposedAwardResponse> createGenerateProposedAwardResponse(GenerateProposedAwardResponse value) {
        return new JAXBElement<GenerateProposedAwardResponse>(_GenerateProposedAwardResponse_QNAME, GenerateProposedAwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAwardValidHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readAwardValidHistory")
    public JAXBElement<ReadAwardValidHistory> createReadAwardValidHistory(ReadAwardValidHistory value) {
        return new JAXBElement<ReadAwardValidHistory>(_ReadAwardValidHistory_QNAME, ReadAwardValidHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HClaimsVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "HClaims")
    public JAXBElement<HClaimsVO> createHClaims(HClaimsVO value) {
        return new JAXBElement<HClaimsVO>(_HClaims_QNAME, HClaimsVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindGAOWorksheet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "findGAOWorksheet")
    public JAXBElement<FindGAOWorksheet> createFindGAOWorksheet(FindGAOWorksheet value) {
        return new JAXBElement<FindGAOWorksheet>(_FindGAOWorksheet_QNAME, FindGAOWorksheet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAwardHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readAwardHistoryResponse")
    public JAXBElement<ReadAwardHistoryResponse> createReadAwardHistoryResponse(ReadAwardHistoryResponse value) {
        return new JAXBElement<ReadAwardHistoryResponse>(_ReadAwardHistoryResponse_QNAME, ReadAwardHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateParticipantAwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "createParticipantAwardResponse")
    public JAXBElement<CreateParticipantAwardResponse> createCreateParticipantAwardResponse(CreateParticipantAwardResponse value) {
        return new JAXBElement<CreateParticipantAwardResponse>(_CreateParticipantAwardResponse_QNAME, CreateParticipantAwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardKeyInputVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardKeyInput")
    public JAXBElement<AwardKeyInputVO> createAwardKeyInput(AwardKeyInputVO value) {
        return new JAXBElement<AwardKeyInputVO>(_AwardKeyInput_QNAME, AwardKeyInputVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecipientEventVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "RecipientEvent")
    public JAXBElement<RecipientEventVO> createRecipientEvent(RecipientEventVO value) {
        return new JAXBElement<RecipientEventVO>(_RecipientEvent_QNAME, RecipientEventVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardClaimRelationshipVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardClaimRelationship")
    public JAXBElement<AwardClaimRelationshipVO> createAwardClaimRelationship(AwardClaimRelationshipVO value) {
        return new JAXBElement<AwardClaimRelationshipVO>(_AwardClaimRelationship_QNAME, AwardClaimRelationshipVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardHistoryVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardHistory")
    public JAXBElement<AwardHistoryVO> createAwardHistory(AwardHistoryVO value) {
        return new JAXBElement<AwardHistoryVO>(_AwardHistory_QNAME, AwardHistoryVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationResponseVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AuthorizationProposedResponse")
    public JAXBElement<AuthorizationResponseVO> createAuthorizationProposedResponse(AuthorizationResponseVO value) {
        return new JAXBElement<AuthorizationResponseVO>(_AuthorizationProposedResponse_QNAME, AuthorizationResponseVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardEventStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardEventStatusResponse")
    public JAXBElement<AwardEventStatusResponse> createAwardEventStatusResponse(AwardEventStatusResponse value) {
        return new JAXBElement<AwardEventStatusResponse>(_AwardEventStatusResponse_QNAME, AwardEventStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardEventID")
    public JAXBElement<String> createAwardEventID(String value) {
        return new JAXBElement<String>(_AwardEventID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardReasonVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardReason")
    public JAXBElement<AwardReasonVO> createAwardReason(AwardReasonVO value) {
        return new JAXBElement<AwardReasonVO>(_AwardReason_QNAME, AwardReasonVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardEventVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardEventInput")
    public JAXBElement<AwardEventVO> createAwardEventInput(AwardEventVO value) {
        return new JAXBElement<AwardEventVO>(_AwardEventInput_QNAME, AwardEventVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClaimVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "Claim")
    public JAXBElement<ClaimVO> createClaim(ClaimVO value) {
        return new JAXBElement<ClaimVO>(_Claim_QNAME, ClaimVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "Message")
    public JAXBElement<MessageVO> createMessage(MessageVO value) {
        return new JAXBElement<MessageVO>(_Message_QNAME, MessageVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardEventVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardEvent")
    public JAXBElement<AwardEventVO> createAwardEvent(AwardEventVO value) {
        return new JAXBElement<AwardEventVO>(_AwardEvent_QNAME, AwardEventVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadDisallowanceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readDisallowanceResponse")
    public JAXBElement<ReadDisallowanceResponse> createReadDisallowanceResponse(ReadDisallowanceResponse value) {
        return new JAXBElement<ReadDisallowanceResponse>(_ReadDisallowanceResponse_QNAME, ReadDisallowanceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "Response")
    public JAXBElement<ResponseVO> createResponse(ResponseVO value) {
        return new JAXBElement<ResponseVO>(_Response_QNAME, ResponseVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadCurrentAndProposedAward }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readCurrentAndProposedAward")
    public JAXBElement<ReadCurrentAndProposedAward> createReadCurrentAndProposedAward(ReadCurrentAndProposedAward value) {
        return new JAXBElement<ReadCurrentAndProposedAward>(_ReadCurrentAndProposedAward_QNAME, ReadCurrentAndProposedAward.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationResponseVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AuthorizationResponse")
    public JAXBElement<AuthorizationResponseVO> createAuthorizationResponse(AuthorizationResponseVO value) {
        return new JAXBElement<AuthorizationResponseVO>(_AuthorizationResponse_QNAME, AuthorizationResponseVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardClaimantVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardClaimant")
    public JAXBElement<AwardClaimantVO> createAwardClaimant(AwardClaimantVO value) {
        return new JAXBElement<AwardClaimantVO>(_AwardClaimant_QNAME, AwardClaimantVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataValidationFaultBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.arch.soap/webfault", name = "DataValidationFaultBean")
    public JAXBElement<DataValidationFaultBean> createDataValidationFaultBean(DataValidationFaultBean value) {
        return new JAXBElement<DataValidationFaultBean>(_DataValidationFaultBean_QNAME, DataValidationFaultBean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProposedAwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "ProposedAwardResponse")
    public JAXBElement<ProposedAwardResponse> createProposedAwardResponse(ProposedAwardResponse value) {
        return new JAXBElement<ProposedAwardResponse>(_ProposedAwardResponse_QNAME, ProposedAwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationEventVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AuthorizationEvent")
    public JAXBElement<AuthorizationEventVO> createAuthorizationEvent(AuthorizationEventVO value) {
        return new JAXBElement<AuthorizationEventVO>(_AuthorizationEvent_QNAME, AuthorizationEventVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BenefitsFaultBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.arch.soap/webfault", name = "BenefitsFaultBean")
    public JAXBElement<BenefitsFaultBean> createBenefitsFaultBean(BenefitsFaultBean value) {
        return new JAXBElement<BenefitsFaultBean>(_BenefitsFaultBean_QNAME, BenefitsFaultBean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardLetterDataResponseVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardLetterDataResponse")
    public JAXBElement<AwardLetterDataResponseVO> createAwardLetterDataResponse(AwardLetterDataResponseVO value) {
        return new JAXBElement<AwardLetterDataResponseVO>(_AwardLetterDataResponse_QNAME, AwardLetterDataResponseVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BenefitsFaultBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.arch.soap/webfault", name = "BenefitsFault")
    public JAXBElement<BenefitsFaultBean> createBenefitsFault(BenefitsFaultBean value) {
        return new JAXBElement<BenefitsFaultBean>(_BenefitsFault_QNAME, BenefitsFaultBean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurrAndPropAwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "CurrAndPropAwardResponse")
    public JAXBElement<CurrAndPropAwardResponse> createCurrAndPropAwardResponse(CurrAndPropAwardResponse value) {
        return new JAXBElement<CurrAndPropAwardResponse>(_CurrAndPropAwardResponse_QNAME, CurrAndPropAwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardClaimRelationshipDetailVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "AwardClaimDetail")
    public JAXBElement<AwardClaimRelationshipDetailVO> createAwardClaimDetail(AwardClaimRelationshipDetailVO value) {
        return new JAXBElement<AwardClaimRelationshipDetailVO>(_AwardClaimDetail_QNAME, AwardClaimRelationshipDetailVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GaoWorksheetVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "GAOWorksheet")
    public JAXBElement<GaoWorksheetVO> createGAOWorksheet(GaoWorksheetVO value) {
        return new JAXBElement<GaoWorksheetVO>(_GAOWorksheet_QNAME, GaoWorksheetVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "VeteranId")
    public JAXBElement<String> createVeteranId(String value) {
        return new JAXBElement<String>(_VeteranId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GAOWorksheetResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "GAOWorksheetResponse")
    public JAXBElement<GAOWorksheetResponse> createGAOWorksheetResponse(GAOWorksheetResponse value) {
        return new JAXBElement<GAOWorksheetResponse>(_GAOWorksheetResponse_QNAME, GAOWorksheetResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConcurProposedAward }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "concurProposedAward")
    public JAXBElement<ConcurProposedAward> createConcurProposedAward(ConcurProposedAward value) {
        return new JAXBElement<ConcurProposedAward>(_ConcurProposedAward_QNAME, ConcurProposedAward.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardRecipientVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardRecipient")
    public JAXBElement<AwardRecipientVO> createAwardRecipient(AwardRecipientVO value) {
        return new JAXBElement<AwardRecipientVO>(_AwardRecipient_QNAME, AwardRecipientVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HAwardEventDataVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "HAwardEventData")
    public JAXBElement<HAwardEventDataVO> createHAwardEventData(HAwardEventDataVO value) {
        return new JAXBElement<HAwardEventDataVO>(_HAwardEventData_QNAME, HAwardEventDataVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadAwardHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readAwardHistory")
    public JAXBElement<ReadAwardHistory> createReadAwardHistory(ReadAwardHistory value) {
        return new JAXBElement<ReadAwardHistory>(_ReadAwardHistory_QNAME, ReadAwardHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnProposedAwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "returnProposedAwardResponse")
    public JAXBElement<ReturnProposedAwardResponse> createReturnProposedAwardResponse(ReturnProposedAwardResponse value) {
        return new JAXBElement<ReturnProposedAwardResponse>(_ReturnProposedAwardResponse_QNAME, ReturnProposedAwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardLineRecipientVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardLineRecipient")
    public JAXBElement<AwardLineRecipientVO> createAwardLineRecipient(AwardLineRecipientVO value) {
        return new JAXBElement<AwardLineRecipientVO>(_AwardLineRecipient_QNAME, AwardLineRecipientVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryServicePeriodVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "MilitaryServicePeriod")
    public JAXBElement<MilitaryServicePeriodVO> createMilitaryServicePeriod(MilitaryServicePeriodVO value) {
        return new JAXBElement<MilitaryServicePeriodVO>(_MilitaryServicePeriod_QNAME, MilitaryServicePeriodVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataValidationFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.arch.soap/webfault", name = "DataValidationFault")
    public JAXBElement<DataValidationFault> createDataValidationFault(DataValidationFault value) {
        return new JAXBElement<DataValidationFault>(_DataValidationFault_QNAME, DataValidationFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadCurrentAndProposedAwardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readCurrentAndProposedAwardResponse")
    public JAXBElement<ReadCurrentAndProposedAwardResponse> createReadCurrentAndProposedAwardResponse(ReadCurrentAndProposedAwardResponse value) {
        return new JAXBElement<ReadCurrentAndProposedAwardResponse>(_ReadCurrentAndProposedAwardResponse_QNAME, ReadCurrentAndProposedAwardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadSuspendResumeHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readSuspendResumeHistoryResponse")
    public JAXBElement<ReadSuspendResumeHistoryResponse> createReadSuspendResumeHistoryResponse(ReadSuspendResumeHistoryResponse value) {
        return new JAXBElement<ReadSuspendResumeHistoryResponse>(_ReadSuspendResumeHistoryResponse_QNAME, ReadSuspendResumeHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadDisallowance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "readDisallowance")
    public JAXBElement<ReadDisallowance> createReadDisallowance(ReadDisallowance value) {
        return new JAXBElement<ReadDisallowance>(_ReadDisallowance_QNAME, ReadDisallowance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardProfileVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "AwardProfile")
    public JAXBElement<AwardProfileVO> createAwardProfile(AwardProfileVO value) {
        return new JAXBElement<AwardProfileVO>(_AwardProfile_QNAME, AwardProfileVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/data", name = "BeneficiaryId")
    public JAXBElement<String> createBeneficiaryId(String value) {
        return new JAXBElement<String>(_BeneficiaryId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardEventDataVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gov.va.vba.benefits.awards.ws/services", name = "awardEventData")
    public JAXBElement<AwardEventDataVO> createAwardEventData(AwardEventDataVO value) {
        return new JAXBElement<AwardEventDataVO>(_AwardEventData_QNAME, AwardEventDataVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "databaseMessage", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanDatabaseMessage(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanDatabaseMessage_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modifiedLocation", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanModifiedLocation(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanModifiedLocation_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sourceErrorID", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanSourceErrorID(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanSourceErrorID_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modifiedProcess", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanModifiedProcess(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanModifiedProcess_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modifiedBy", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanModifiedBy(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanModifiedBy_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "object", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanObject(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanObject_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modifiedDate", scope = BenefitsFaultBean.class)
    public JAXBElement<XMLGregorianCalendar> createBenefitsFaultBeanModifiedDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_BenefitsFaultBeanModifiedDate_QNAME, XMLGregorianCalendar.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modifiedAction", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanModifiedAction(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanModifiedAction_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exceptionInfo", scope = BenefitsFaultBean.class)
    public JAXBElement<MessageVO> createBenefitsFaultBeanExceptionInfo(MessageVO value) {
        return new JAXBElement<MessageVO>(_BenefitsFaultBeanExceptionInfo_QNAME, MessageVO.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "messageID", scope = BenefitsFaultBean.class)
    public JAXBElement<Integer> createBenefitsFaultBeanMessageID(Integer value) {
        return new JAXBElement<Integer>(_BenefitsFaultBeanMessageID_QNAME, Integer.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanSource(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanSource_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "logIt", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanLogIt(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanLogIt_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldName", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanFieldName(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanFieldName_QNAME, String.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rowIdentifier", scope = BenefitsFaultBean.class)
    public JAXBElement<Long> createBenefitsFaultBeanRowIdentifier(Long value) {
        return new JAXBElement<Long>(_BenefitsFaultBeanRowIdentifier_QNAME, Long.class, BenefitsFaultBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sourceMessage", scope = BenefitsFaultBean.class)
    public JAXBElement<String> createBenefitsFaultBeanSourceMessage(String value) {
        return new JAXBElement<String>(_BenefitsFaultBeanSourceMessage_QNAME, String.class, BenefitsFaultBean.class, value);
    }

}
